/*
 * © 2025 Sphereon International B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.sphereon.crypto.core.kms

import com.sphereon.crypto.core.generic.KeyTypeMapping
import com.sphereon.crypto.core.kms.model.IdentifierMethod
import com.sphereon.core.compat.Uuid

/**
 * Default base class for key resolver services.
 *
 * This class provides common functionality for resolving cryptographic keys.
 *
 * @property id Unique identifier for the session instance, generated by default.
 * @property supported A map that associates identifier methods with arrays of supported key types.
 */
abstract class AbstractKeyResolverService(
    private val id: String = Uuid.v4String(),
    private val supported: Map<IdentifierMethod, Array<KeyTypeMapping>>
) : KeyResolverService {

    override fun getId() = id
    override fun allSupportedIdentifierMethods(): Array<IdentifierMethod> = supported.keys.toTypedArray()
    override fun allSupportedKeyTypes(): Array<KeyTypeMapping> = supported.flatMap { it.value.toSet() }.toSet().toTypedArray()
    override fun supportedKeyTypesAndIdentifierMethods(): Map<IdentifierMethod, Array<KeyTypeMapping>> = supported

    override fun getSupportedKeyTypes(identifierMethod: IdentifierMethod): Array<KeyTypeMapping> = supported[identifierMethod] ?: emptyArray()

    override fun getSupportedIdentifierMethods(keyType: KeyTypeMapping): Array<IdentifierMethod> =
        supported.filter { it.value.contains(keyType) }.keys.toTypedArray()

}
