/**
 * System default token maps — wallet-aligned light + dark themes.
 *
 * GENERATED from tokens.json + tokens.dark.json by build/generate-theme-react.mjs.
 * Do NOT hand-edit; change the DTCG source and regenerate.
 *
 * Three-tier: Tier 1 palette primitives, Tier 2 semantic roles, Tier 3 lives in
 * component-token-defaults.ts. Components consume Tier 2 / Tier 3 only.
 */

import type { ThemeTokenMap, ThemeVariant } from './types'

const palettes: ThemeTokenMap = {
  'palette.brand.50': '#ECE4FC',
  'palette.brand.100': '#E0D2FA',
  'palette.brand.200': '#C7ADF5',
  'palette.brand.300': '#AE89F1',
  'palette.brand.400': '#9564EC',
  'palette.brand.500': '#7C40E8',
  'palette.brand.600': '#5D1AD6',
  'palette.brand.700': '#4714A4',
  'palette.brand.800': '#320E72',
  'palette.brand.900': '#1C0840',
  'palette.gray.50': '#FBFBFB',
  'palette.gray.100': '#F2F2F2',
  'palette.gray.200': '#E3E3E3',
  'palette.gray.300': '#C4C4C4',
  'palette.gray.400': '#969696',
  'palette.gray.500': '#585858',
  'palette.gray.600': '#727272',
  'palette.gray.700': '#4E4E4E',
  'palette.gray.800': '#303030',
  'palette.gray.900': '#0A0D12',
  'palette.blue.50': '#D8DDEB',
  'palette.blue.100': '#CBD1E4',
  'palette.blue.200': '#B0B9D6',
  'palette.blue.300': '#96A1C8',
  'palette.blue.400': '#6071AC',
  'palette.blue.500': '#4E5E95',
  'palette.blue.600': '#404D7A',
  'palette.blue.700': '#2D3655',
  'palette.blue.800': '#2C334B',
  'palette.blue.900': '#202537',
  'palette.error.50': '#FFF6F3',
  'palette.error.100': '#FFEAE3',
  'palette.error.200': '#FFD0C0',
  'palette.error.300': '#F2A091',
  'palette.error.400': '#DB7759',
  'palette.error.500': '#D14500',
  'palette.error.600': '#B53A00',
  'palette.error.700': '#8E2D06',
  'palette.error.800': '#52190B',
  'palette.error.900': '#320C04',
  'palette.warning.50': '#FFFAEB',
  'palette.warning.100': '#FEEDC7',
  'palette.warning.200': '#FEDFB9',
  'palette.warning.300': '#FECB4B',
  'palette.warning.400': '#FDB922',
  'palette.warning.500': '#E0B910',
  'palette.warning.600': '#DC9A02',
  'palette.warning.700': '#985A0B',
  'palette.warning.800': '#674A0D',
  'palette.warning.900': '#412D05',
  'palette.success.50': '#CCFFDF',
  'palette.success.100': '#B8FFD3',
  'palette.success.200': '#8BFFB9',
  'palette.success.300': '#66BFA0',
  'palette.success.400': '#15FF5D',
  'palette.success.500': '#00E963',
  'palette.success.600': '#00C249',
  'palette.success.700': '#006B34',
  'palette.success.800': '#005C2F',
  'palette.success.900': '#003516',
  'palette.pending.50': '#D7EAFF',
  'palette.pending.100': '#AED5FF',
  'palette.pending.200': '#85C0FF',
  'palette.pending.300': '#5DABFF',
  'palette.pending.400': '#3496FF',
  'palette.pending.500': '#0B81FF',
  'palette.pending.600': '#0066D2',
  'palette.pending.700': '#004A9A',
  'palette.pending.800': '#002F62',
  'palette.pending.900': '#002246',
  'palette.aqua.50': '#E3F9F7',
  'palette.aqua.100': '#C1F3EE',
  'palette.aqua.200': '#9FECE5',
  'palette.aqua.300': '#7DE5DB',
  'palette.aqua.400': '#5BDED2',
  'palette.aqua.500': '#2CD5C5',
  'palette.aqua.600': '#22A79B',
  'palette.aqua.700': '#187870',
  'palette.aqua.800': '#0F4A44',
  'palette.aqua.900': '#0A322F',
  'palette.selenas.50': '#F4E3F9',
  'palette.selenas.100': '#E6C1F3',
  'palette.selenas.200': '#D89FEC',
  'palette.selenas.300': '#CA7DE5',
  'palette.selenas.400': '#BC5BDE',
  'palette.selenas.500': '#A92CD5',
  'palette.selenas.600': '#8522A7',
  'palette.selenas.700': '#5F1878',
  'palette.selenas.800': '#3A0F4A',
  'palette.selenas.900': '#280A32',
  'palette.magenta.50': '#FFD0DB',
  'palette.magenta.100': '#FFA7BC',
  'palette.magenta.200': '#FF7F9D',
  'palette.magenta.300': '#FF567E',
  'palette.magenta.400': '#FF2D5F',
  'palette.magenta.500': '#F4003A',
  'palette.magenta.600': '#BC002D',
  'palette.magenta.700': '#84001F',
  'palette.magenta.800': '#4C0012',
  'palette.magenta.900': '#30000B',
  'palette.purple.50': '#E7DEFB',
  'palette.purple.100': '#CBBAF6',
  'palette.purple.200': '#B096F2',
  'palette.purple.300': '#9571ED',
  'palette.purple.400': '#7A4DE9',
  'palette.purple.500': '#551CE2',
  'palette.purple.600': '#4216B0',
  'palette.purple.700': '#2F107E',
  'palette.purple.800': '#1D094C',
  'palette.purple.900': '#130633',
}

const sharedTokens: ThemeTokenMap = {
  ...palettes,
  'elevation.none': '0dp',
  'elevation.xs': '1dp',
  'elevation.sm': '3dp',
  'elevation.md': '6dp',
  'elevation.lg': '8dp',
  'elevation.xl': '12dp',
  'text.family.sans': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'text.family.secondary': '\'Plus Jakarta Sans\', Poppins, system-ui, sans-serif',
  'text.family.meta': 'Inter, system-ui, sans-serif',
  'text.family.mono': 'ui-monospace, \'SF Mono\', \'Menlo\', \'Consolas\', \'Liberation Mono\', monospace',
  'text.style.xl.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'text.style.xl.fontSize': '46sp',
  'text.style.xl.fontWeight': '600',
  'text.style.xl.lineHeight': '54sp',
  'text.style.xl.desktop.fontSize': '56sp',
  'text.style.xl.desktop.lineHeight': '64sp',
  'text.style.h1.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'text.style.h1.fontSize': '24sp',
  'text.style.h1.fontWeight': '600',
  'text.style.h1.lineHeight': '36sp',
  'text.style.h1.desktop.fontSize': '32sp',
  'text.style.h1.desktop.lineHeight': '40sp',
  'text.style.h2.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'text.style.h2.fontSize': '16sp',
  'text.style.h2.fontWeight': '600',
  'text.style.h2.lineHeight': '24sp',
  'text.style.h2.desktop.fontSize': '20sp',
  'text.style.h2.desktop.lineHeight': '28sp',
  'text.style.h3.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'text.style.h3.fontSize': '16sp',
  'text.style.h3.fontWeight': '400',
  'text.style.h3.lineHeight': '24sp',
  'text.style.h3.desktop.fontSize': '18sp',
  'text.style.h3.desktop.lineHeight': '26sp',
  'text.style.subtitle1.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'text.style.subtitle1.fontSize': '14sp',
  'text.style.subtitle1.fontWeight': '600',
  'text.style.subtitle1.lineHeight': '21sp',
  'text.style.subtitle1.desktop.fontSize': '16sp',
  'text.style.subtitle1.desktop.lineHeight': '24sp',
  'text.style.subtitle2.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'text.style.subtitle2.fontSize': '11sp',
  'text.style.subtitle2.fontWeight': '600',
  'text.style.subtitle2.lineHeight': '17sp',
  'text.style.subtitle2.desktop.fontSize': '14sp',
  'text.style.subtitle2.desktop.lineHeight': '20sp',
  'text.style.body1.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'text.style.body1.fontSize': '12sp',
  'text.style.body1.fontWeight': '400',
  'text.style.body1.lineHeight': '21sp',
  'text.style.body1.desktop.fontSize': '14sp',
  'text.style.body1.desktop.lineHeight': '22sp',
  'text.style.micro1.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'text.style.micro1.fontSize': '10sp',
  'text.style.micro1.fontWeight': '400',
  'text.style.micro1.lineHeight': '15sp',
  'text.style.micro1.desktop.fontSize': '12sp',
  'text.style.micro1.desktop.lineHeight': '18sp',
  'text.style.micro2.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'text.style.micro2.fontSize': '9sp',
  'text.style.micro2.fontWeight': '400',
  'text.style.micro2.lineHeight': '15sp',
  'text.style.micro2.desktop.fontSize': '11sp',
  'text.style.micro2.desktop.lineHeight': '16sp',
  'typography.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.fontFamilyMono': 'ui-monospace, \'SF Mono\', \'Menlo\', \'Consolas\', \'Liberation Mono\', monospace',
  'typography.displayExtraLarge.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.displayExtraLarge.fontSize': '46sp',
  'typography.displayExtraLarge.fontWeight': '600',
  'typography.displayExtraLarge.lineHeight': '54sp',
  'typography.displayExtraLarge.letterSpacing': '0sp',
  'typography.displayLarge.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.displayLarge.fontSize': '46sp',
  'typography.displayLarge.fontWeight': '600',
  'typography.displayLarge.lineHeight': '54sp',
  'typography.displayLarge.letterSpacing': '0sp',
  'typography.displayMedium.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.displayMedium.fontSize': '32sp',
  'typography.displayMedium.fontWeight': '600',
  'typography.displayMedium.lineHeight': '40sp',
  'typography.displayMedium.letterSpacing': '0sp',
  'typography.displaySmall.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.displaySmall.fontSize': '24sp',
  'typography.displaySmall.fontWeight': '600',
  'typography.displaySmall.lineHeight': '36sp',
  'typography.displaySmall.letterSpacing': '0sp',
  'typography.headlineLarge.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.headlineLarge.fontSize': '24sp',
  'typography.headlineLarge.fontWeight': '600',
  'typography.headlineLarge.lineHeight': '36sp',
  'typography.headlineLarge.letterSpacing': '0sp',
  'typography.headlineMedium.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.headlineMedium.fontSize': '20sp',
  'typography.headlineMedium.fontWeight': '600',
  'typography.headlineMedium.lineHeight': '30sp',
  'typography.headlineMedium.letterSpacing': '0sp',
  'typography.headlineSmall.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.headlineSmall.fontSize': '18sp',
  'typography.headlineSmall.fontWeight': '600',
  'typography.headlineSmall.lineHeight': '27sp',
  'typography.headlineSmall.letterSpacing': '0sp',
  'typography.titleLarge.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.titleLarge.fontSize': '16sp',
  'typography.titleLarge.fontWeight': '600',
  'typography.titleLarge.lineHeight': '24sp',
  'typography.titleLarge.letterSpacing': '0sp',
  'typography.titleMedium.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.titleMedium.fontSize': '16sp',
  'typography.titleMedium.fontWeight': '400',
  'typography.titleMedium.lineHeight': '24sp',
  'typography.titleMedium.letterSpacing': '0sp',
  'typography.titleSmall.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.titleSmall.fontSize': '14sp',
  'typography.titleSmall.fontWeight': '600',
  'typography.titleSmall.lineHeight': '21sp',
  'typography.titleSmall.letterSpacing': '0sp',
  'typography.bodyLarge.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.bodyLarge.fontSize': '14sp',
  'typography.bodyLarge.fontWeight': '400',
  'typography.bodyLarge.lineHeight': '21sp',
  'typography.bodyLarge.letterSpacing': '0sp',
  'typography.bodyMedium.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.bodyMedium.fontSize': '12sp',
  'typography.bodyMedium.fontWeight': '400',
  'typography.bodyMedium.lineHeight': '21sp',
  'typography.bodyMedium.letterSpacing': '0sp',
  'typography.bodySmall.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.bodySmall.fontSize': '10sp',
  'typography.bodySmall.fontWeight': '400',
  'typography.bodySmall.lineHeight': '15sp',
  'typography.bodySmall.letterSpacing': '0sp',
  'typography.bodyExtraSmall.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.bodyExtraSmall.fontSize': '9sp',
  'typography.bodyExtraSmall.fontWeight': '400',
  'typography.bodyExtraSmall.lineHeight': '15sp',
  'typography.bodyExtraSmall.letterSpacing': '0sp',
  'typography.labelLarge.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.labelLarge.fontSize': '14sp',
  'typography.labelLarge.fontWeight': '600',
  'typography.labelLarge.lineHeight': '21sp',
  'typography.labelLarge.letterSpacing': '0sp',
  'typography.labelMedium.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.labelMedium.fontSize': '12sp',
  'typography.labelMedium.fontWeight': '500',
  'typography.labelMedium.lineHeight': '21sp',
  'typography.labelMedium.letterSpacing': '0sp',
  'typography.labelSmall.fontFamily': 'Poppins, \'Plus Jakarta Sans\', system-ui, sans-serif',
  'typography.labelSmall.fontSize': '11sp',
  'typography.labelSmall.fontWeight': '600',
  'typography.labelSmall.lineHeight': '17sp',
  'typography.labelSmall.letterSpacing': '0sp',
  'shape.radius.0': '0dp',
  'shape.radius.1': '2dp',
  'shape.radius.2': '4dp',
  'shape.radius.3': '6dp',
  'shape.radius.4': '8dp',
  'shape.radius.6': '12dp',
  'shape.radius.8': '16dp',
  'shape.radius.12': '24dp',
  'shape.radius.none': '0dp',
  'shape.radius.xs': '2dp',
  'shape.radius.sm': '4dp',
  'shape.radius.md': '8dp',
  'shape.radius.lg': '12dp',
  'shape.radius.xl': '16dp',
  'shape.radius.xxl': '20dp',
  'shape.radius.xxxl': '24dp',
  'shape.radius.full': '9999dp',
  'shape.cornerExtraSmall': '4dp',
  'shape.cornerSmall': '8dp',
  'shape.cornerMedium': '12dp',
  'shape.cornerLarge': '16dp',
  'shape.cornerExtraLarge': '24dp',
  'motion.duration.short1': '50ms',
  'motion.duration.short2': '100ms',
  'motion.duration.short3': '150ms',
  'motion.duration.short4': '200ms',
  'motion.duration.medium1': '250ms',
  'motion.duration.medium2': '300ms',
  'motion.duration.medium3': '350ms',
  'motion.duration.medium4': '400ms',
  'motion.duration.long1': '450ms',
  'motion.duration.long2': '500ms',
  'motion.duration.long3': '550ms',
  'motion.duration.long4': '600ms',
  'motion.duration.instant': '0ms',
  'motion.duration.fast': '150ms',
  'motion.duration.normal': '200ms',
  'motion.duration.slow': '300ms',
  'motion.duration.slower': '600ms',
  'motion.delay.none': '0ms',
  'motion.delay.short': '100ms',
  'motion.easing.standard': 'cubic-bezier(0.2, 0, 0, 1)',
  'motion.easing.standardDecelerate': 'cubic-bezier(0, 0, 0, 1)',
  'motion.easing.standardAccelerate': 'cubic-bezier(0.3, 0, 1, 1)',
  'motion.easing.emphasized': 'cubic-bezier(0.2, 0, 0, 1)',
  'motion.easing.emphasizedDecelerate': 'cubic-bezier(0.05, 0.7, 0.1, 1)',
  'motion.easing.emphasizedAccelerate': 'cubic-bezier(0.3, 0, 0.8, 0.15)',
  'motion.easing.linear': 'cubic-bezier(0, 0, 1, 1)',
  'motion.easing.bounce': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
  'motion.themeTransition.duration': '300ms',
  'motion.themeTransition.easing': 'cubic-bezier(0.2, 0, 0, 1)',
  'responsive.scale.medium.display': '1.10',
  'responsive.scale.medium.headline': '1.05',
  'responsive.scale.expanded.display': '1.20',
  'responsive.scale.expanded.headline': '1.10',
  'responsive.scale.expanded.title': '1.05',
  'spacing.0': '0px',
  'spacing.1': '4px',
  'spacing.2': '8px',
  'spacing.3': '12px',
  'spacing.4': '16px',
  'spacing.5': '20px',
  'spacing.6': '24px',
  'spacing.7': '28px',
  'spacing.8': '32px',
  'spacing.9': '36px',
  'spacing.10': '40px',
  'spacing.11': '44px',
  'spacing.12': '48px',
  'spacing.14': '56px',
  'spacing.16': '64px',
  'spacing.20': '80px',
  'spacing.24': '96px',
  'spacing.28': '112px',
  'spacing.32': '128px',
  'spacing.36': '144px',
  'spacing.40': '160px',
  'spacing.44': '176px',
  'spacing.48': '192px',
  'spacing.52': '208px',
  'spacing.56': '224px',
  'spacing.60': '240px',
  'spacing.64': '256px',
  'spacing.72': '288px',
  'spacing.80': '320px',
  'spacing.96': '384px',
  'spacing.0_5': '2px',
  'spacing.1_5': '6px',
  'spacing.2_5': '10px',
  'spacing.3_5': '14px',
  'spacing.inline.xs': '4px',
  'spacing.inline.sm': '8px',
  'spacing.inline.md': '16px',
  'spacing.inline.lg': '24px',
  'spacing.inline.xl': '32px',
  'spacing.stack.xs': '4px',
  'spacing.stack.sm': '8px',
  'spacing.stack.md': '16px',
  'spacing.stack.lg': '24px',
  'spacing.stack.xl': '32px',
  'spacing.inset.xs': '8px',
  'spacing.inset.sm': '12px',
  'spacing.inset.md': '16px',
  'spacing.inset.lg': '24px',
  'spacing.inset.xl': '32px',
  'borderWidth.none': '0px',
  'borderWidth.thin': '1px',
  'borderWidth.medium': '2px',
  'borderWidth.thick': '4px',
  'shadow.100': '0 1px 2px rgba(10,13,18,0.05)',
  'shadow.200': '0 2px 4px rgba(0,0,0,0.10)',
  'shadow.300': '0 4px 8px rgba(0,0,0,0.12)',
  'shadow.400': '0 12px 24px rgba(10,13,18,0.16)',
  'shadow.elevation.none': 'none',
  'shadow.elevation.xs': '0 1px 2px rgba(10,13,18,0.05)',
  'shadow.elevation.sm': '0 2px 4px rgba(0,0,0,0.10)',
  'shadow.elevation.md': '0 4px 8px rgba(0,0,0,0.12)',
  'shadow.elevation.lg': '0 12px 24px rgba(10,13,18,0.16)',
  'shadow.elevation.xl': '0 24px 48px rgba(10,13,18,0.20)',
  'shadow.elevation.xxl': '0 25px 50px -12px rgba(0,0,0,0.25)',
  'shadow.subtle': '0 1px 2px rgba(10,13,18,0.05)',
  'shadow.raised': '0 2px 4px rgba(0,0,0,0.10)',
  'shadow.floating': '0 4px 8px rgba(0,0,0,0.12)',
  'shadow.overlay': '0 12px 24px rgba(10,13,18,0.16)',
  'shadow.dramatic': '0 25px 50px -12px rgba(0,0,0,0.25)',
  'shadow.state.focus': '0 0 0 3px rgba(11,129,255,0.5)',
  'shadow.state.error': '0 0 0 3px rgba(181,58,0,0.5)',
  'shadow.state.active': 'inset 0 2px 4px rgba(0,0,0,0.16)',
  'shadow.state.selected': '0 0 0 2px rgba(124,64,232,0.3)',
  'a11y.targetSizeMin': '44px',
}

const lightColors: ThemeTokenMap = {
  'color.primary': '#7C40E8',
  'color.onPrimary': '#FBFBFB',
  'color.primaryContainer': '#ECE4FC',
  'color.onPrimaryContainer': '#320E72',
  'color.navigation.activeForeground': '{palette.brand.700}',
  'color.accent': '#7C40E8',
  'color.secondary': '#4E5E95',
  'color.onSecondary': '#FFFFFF',
  'color.secondaryContainer': '#D8DDEB',
  'color.onSecondaryContainer': '#2C334B',
  'color.tertiary': '#A92CD5',
  'color.onTertiary': '#FBFBFB',
  'color.tertiaryContainer': '#F4E3F9',
  'color.onTertiaryContainer': '#3A0F4A',
  'color.error': '#B53A00',
  'color.onError': '#FFFFFF',
  'color.errorContainer': '#FFF6F3',
  'color.onErrorContainer': '#8E2D06',
  'color.surface': '#FFFFFF',
  'color.onSurface': '#0A0D12',
  'color.surfaceVariant': '#F2F2F2',
  'color.onSurfaceVariant': '#4E4E4E',
  'color.surfaceContainer': '#F2F2F2',
  'color.surfaceContainerHigh': '#E3E3E3',
  'color.surfaceContainerHighest': '#C4C4C4',
  'color.surfaceContainerLow': '#FBFBFB',
  'color.surfaceContainerLowest': '#FFFFFF',
  'color.background': '#FBFBFB',
  'color.onBackground': '#0A0D12',
  'color.outline': '#C4C4C4',
  'color.outlineVariant': '#E3E3E3',
  'color.inverseSurface': '#202537',
  'color.inverseOnSurface': '#FBFBFB',
  'color.inversePrimary': '#AE89F1',
  'color.scrim': 'rgba(10,13,18,0.5)',
  'color.shadow': 'rgba(10,13,18,0.16)',
  'color.interactive.hover': '#F2F2F2',
  'color.interactive.pressed': '#E3E3E3',
  'color.interactive.disabled': '#E3E3E3',
  'color.interactive.focus': '#7C40E8',
  'color.feedback.success': '#00C249',
  'color.feedback.successContainer': '#CCFFDF',
  'color.feedback.onSuccess': '#FFFFFF',
  'color.feedback.onSuccessContainer': '#003516',
  'color.feedback.successBorder': '#8BFFB9',
  'color.feedback.warning': '#DC9A02',
  'color.feedback.warningContainer': '#FFFAEB',
  'color.feedback.onWarning': '#0A0D12',
  'color.feedback.onWarningContainer': '#985A0B',
  'color.feedback.warningBorder': '#FEDFB9',
  'color.feedback.info': '#0B81FF',
  'color.feedback.infoContainer': '#D7EAFF',
  'color.feedback.onInfo': '#FFFFFF',
  'color.feedback.onInfoContainer': '#002246',
  'color.feedback.infoBorder': '#85C0FF',
  'color.feedback.errorContainer': '#FFF6F3',
  'color.feedback.onErrorContainer': '#8E2D06',
  'color.feedback.errorBorder': '#FFD0C0',
  'color.text.primary': '#0A0D12',
  'color.text.secondary': '#4E4E4E',
  'color.text.disabled': '#969696',
  'color.text.inverse': '#FBFBFB',
  'color.border.default': '#C4C4C4',
  'color.border.strong': '#4E4E4E',
  'color.border.subtle': '#E3E3E3',
  'color.border.disabled': '#E3E3E3',
}

const darkColors: ThemeTokenMap = {
  'color.primary': '#7C40E8',
  'color.onPrimary': '#FFFFFF',
  'color.primaryContainer': 'color-mix(in srgb, {palette.brand.500} 18%, transparent)',
  'color.onPrimaryContainer': '#E0D2FA',
  'color.navigation.activeForeground': '{color.onPrimary}',
  'color.accent': '#7C40E8',
  'color.secondary': '#C7ADF5',
  'color.onSecondary': '#202537',
  'color.secondaryContainer': '#1D212C',
  'color.onSecondaryContainer': '#E0D2FA',
  'color.tertiary': '#CA7DE5',
  'color.onTertiary': '#280A32',
  'color.tertiaryContainer': '#3A0F4A',
  'color.onTertiaryContainer': '#E6C1F3',
  'color.error': '#DB7759',
  'color.onError': '#320C04',
  'color.errorContainer': '#52190B',
  'color.onErrorContainer': '#FFEAE3',
  'color.surface': '#161922',
  'color.onSurface': '#ECECF1',
  'color.surfaceVariant': '#1D212C',
  'color.onSurfaceVariant': '#8B8FA3',
  'color.surfaceContainer': '#12151D',
  'color.surfaceContainerHigh': '#1D212C',
  'color.surfaceContainerHighest': '#1D212C',
  'color.surfaceContainerLow': '#161922',
  'color.surfaceContainerLowest': '#0D0F14',
  'color.background': '#0D0F14',
  'color.onBackground': '#ECECF1',
  'color.inverseSurface': '#FBFBFB',
  'color.inverseOnSurface': '#0A0D12',
  'color.inversePrimary': '#7C40E8',
  'color.outline': '#2A2F3A',
  'color.outlineVariant': '#22262F',
  'color.scrim': 'rgba(0,0,0,0.7)',
  'color.shadow': 'rgba(0,0,0,0.5)',
  'color.interactive.hover': 'color-mix(in srgb, {color.onPrimary} 6%, transparent)',
  'color.interactive.pressed': 'color-mix(in srgb, {color.onPrimary} 10%, transparent)',
  'color.interactive.disabled': '#1D212C',
  'color.interactive.focus': '#7C40E8',
  'color.feedback.success': '#15FF5D',
  'color.feedback.successContainer': 'color-mix(in srgb, {palette.success.500} 12%, transparent)',
  'color.feedback.onSuccess': '#003516',
  'color.feedback.onSuccessContainer': '#5FE39B',
  'color.feedback.successBorder': 'color-mix(in srgb, {palette.success.300} 28%, transparent)',
  'color.feedback.warning': '#FDB922',
  'color.feedback.warningContainer': 'color-mix(in srgb, {palette.warning.400} 12%, transparent)',
  'color.feedback.onWarning': '#412D05',
  'color.feedback.onWarningContainer': '#F4C24E',
  'color.feedback.warningBorder': 'color-mix(in srgb, {palette.warning.300} 28%, transparent)',
  'color.feedback.info': '#3496FF',
  'color.feedback.infoContainer': 'color-mix(in srgb, {palette.pending.400} 14%, transparent)',
  'color.feedback.onInfo': '#002246',
  'color.feedback.onInfoContainer': '#5DABFF',
  'color.feedback.infoBorder': 'color-mix(in srgb, {palette.pending.300} 28%, transparent)',
  'color.feedback.errorContainer': 'color-mix(in srgb, {palette.error.400} 14%, transparent)',
  'color.feedback.onErrorContainer': '#F0A091',
  'color.feedback.errorBorder': 'color-mix(in srgb, {palette.error.300} 28%, transparent)',
  'color.text.primary': '#ECECF1',
  'color.text.secondary': '#8B8FA3',
  'color.text.disabled': '#5B6070',
  'color.text.inverse': '#0A0D12',
  'color.border.default': '#2A2F3A',
  'color.border.strong': '#E3E3E3',
  'color.border.subtle': '#22262F',
  'color.border.disabled': '#22262F',
  'shadow.elevation.xs': '0 1px 2px rgba(0,0,0,0.4)',
  'shadow.elevation.sm': '0 2px 4px rgba(0,0,0,0.5)',
  'shadow.elevation.md': '0 4px 8px rgba(0,0,0,0.55)',
  'shadow.elevation.lg': '0 12px 24px rgba(0,0,0,0.6)',
  'shadow.subtle': '0 1px 2px rgba(0,0,0,0.4)',
  'shadow.raised': '0 2px 4px rgba(0,0,0,0.5)',
  'shadow.floating': '0 4px 8px rgba(0,0,0,0.55)',
  'shadow.overlay': '0 12px 24px rgba(0,0,0,0.6)',
}

export function getSystemDefaults(variant: ThemeVariant): ThemeTokenMap {
  const colors = variant === 'dark' ? darkColors : lightColors
  return { ...sharedTokens, ...colors }
}
