/**
 * System default token maps — M3 baseline light and dark themes.
 *
 * These are identical to IDK's SystemDefaults.kt and are the root of the
 * resolution chain: every resolved theme starts from these values.
 *
 * In future, when the Kotlin/JS packages are published, this can be replaced
 * with a re-export from @sphereon/theme-web. For now, it's a standalone
 * TypeScript implementation to avoid the Kotlin/JS bundle cost.
 */

import type { ThemeTokenMap, ThemeVariant } from './types'

const sharedTokens: ThemeTokenMap = {
  // Elevation
  'elevation.none': '0dp',
  'elevation.xs': '1dp',
  'elevation.sm': '3dp',
  'elevation.md': '6dp',
  'elevation.lg': '8dp',
  'elevation.xl': '12dp',

  // Typography — generic
  'typography.fontFamily': 'Roboto',
  'typography.fontFamilyMono': 'Roboto Mono',

  // Typography — Display
  'typography.displayLarge.fontFamily': 'Roboto',
  'typography.displayLarge.fontSize': '57sp',
  'typography.displayLarge.fontWeight': '400',
  'typography.displayLarge.lineHeight': '64sp',
  'typography.displayLarge.letterSpacing': '-0.25sp',
  'typography.displayMedium.fontFamily': 'Roboto',
  'typography.displayMedium.fontSize': '45sp',
  'typography.displayMedium.fontWeight': '400',
  'typography.displayMedium.lineHeight': '52sp',
  'typography.displayMedium.letterSpacing': '0sp',
  'typography.displaySmall.fontFamily': 'Roboto',
  'typography.displaySmall.fontSize': '36sp',
  'typography.displaySmall.fontWeight': '400',
  'typography.displaySmall.lineHeight': '44sp',
  'typography.displaySmall.letterSpacing': '0sp',

  // Typography — Headline
  'typography.headlineLarge.fontFamily': 'Roboto',
  'typography.headlineLarge.fontSize': '32sp',
  'typography.headlineLarge.fontWeight': '400',
  'typography.headlineLarge.lineHeight': '40sp',
  'typography.headlineLarge.letterSpacing': '0sp',
  'typography.headlineMedium.fontFamily': 'Roboto',
  'typography.headlineMedium.fontSize': '28sp',
  'typography.headlineMedium.fontWeight': '400',
  'typography.headlineMedium.lineHeight': '36sp',
  'typography.headlineMedium.letterSpacing': '0sp',
  'typography.headlineSmall.fontFamily': 'Roboto',
  'typography.headlineSmall.fontSize': '24sp',
  'typography.headlineSmall.fontWeight': '400',
  'typography.headlineSmall.lineHeight': '32sp',
  'typography.headlineSmall.letterSpacing': '0sp',

  // Typography — Title
  'typography.titleLarge.fontFamily': 'Roboto',
  'typography.titleLarge.fontSize': '22sp',
  'typography.titleLarge.fontWeight': '400',
  'typography.titleLarge.lineHeight': '28sp',
  'typography.titleLarge.letterSpacing': '0sp',
  'typography.titleMedium.fontFamily': 'Roboto',
  'typography.titleMedium.fontSize': '16sp',
  'typography.titleMedium.fontWeight': '500',
  'typography.titleMedium.lineHeight': '24sp',
  'typography.titleMedium.letterSpacing': '0.15sp',
  'typography.titleSmall.fontFamily': 'Roboto',
  'typography.titleSmall.fontSize': '14sp',
  'typography.titleSmall.fontWeight': '500',
  'typography.titleSmall.lineHeight': '20sp',
  'typography.titleSmall.letterSpacing': '0.1sp',

  // Typography — Body
  'typography.bodyLarge.fontFamily': 'Roboto',
  'typography.bodyLarge.fontSize': '16sp',
  'typography.bodyLarge.fontWeight': '400',
  'typography.bodyLarge.lineHeight': '24sp',
  'typography.bodyLarge.letterSpacing': '0.5sp',
  'typography.bodyMedium.fontFamily': 'Roboto',
  'typography.bodyMedium.fontSize': '14sp',
  'typography.bodyMedium.fontWeight': '400',
  'typography.bodyMedium.lineHeight': '20sp',
  'typography.bodyMedium.letterSpacing': '0.25sp',
  'typography.bodySmall.fontFamily': 'Roboto',
  'typography.bodySmall.fontSize': '12sp',
  'typography.bodySmall.fontWeight': '400',
  'typography.bodySmall.lineHeight': '16sp',
  'typography.bodySmall.letterSpacing': '0.4sp',

  // Typography — Label
  'typography.labelLarge.fontFamily': 'Roboto',
  'typography.labelLarge.fontSize': '14sp',
  'typography.labelLarge.fontWeight': '500',
  'typography.labelLarge.lineHeight': '20sp',
  'typography.labelLarge.letterSpacing': '0.1sp',
  'typography.labelMedium.fontFamily': 'Roboto',
  'typography.labelMedium.fontSize': '12sp',
  'typography.labelMedium.fontWeight': '500',
  'typography.labelMedium.lineHeight': '16sp',
  'typography.labelMedium.letterSpacing': '0.5sp',
  'typography.labelSmall.fontFamily': 'Roboto',
  'typography.labelSmall.fontSize': '11sp',
  'typography.labelSmall.fontWeight': '500',
  'typography.labelSmall.lineHeight': '16sp',
  'typography.labelSmall.letterSpacing': '0.5sp',

  // Shape
  'shape.cornerExtraSmall': '4dp',
  'shape.cornerSmall': '8dp',
  'shape.cornerMedium': '12dp',
  'shape.cornerLarge': '16dp',
  'shape.cornerExtraLarge': '28dp',

  // Motion — durations
  'motion.duration.short1': '50ms',
  'motion.duration.short2': '100ms',
  'motion.duration.short3': '150ms',
  'motion.duration.short4': '200ms',
  'motion.duration.medium1': '250ms',
  'motion.duration.medium2': '300ms',
  'motion.duration.medium3': '350ms',
  'motion.duration.medium4': '400ms',
  'motion.duration.long1': '450ms',
  'motion.duration.long2': '500ms',
  'motion.duration.long3': '550ms',
  'motion.duration.long4': '600ms',

  // Motion — easing
  'motion.easing.standard': 'cubic-bezier(0.2, 0.0, 0, 1.0)',
  'motion.easing.standardDecelerate': 'cubic-bezier(0, 0, 0, 1.0)',
  'motion.easing.standardAccelerate': 'cubic-bezier(0.3, 0, 1, 1)',
  'motion.easing.emphasized': 'cubic-bezier(0.2, 0.0, 0, 1.0)',
  'motion.easing.emphasizedDecelerate': 'cubic-bezier(0.05, 0.7, 0.1, 1.0)',
  'motion.easing.emphasizedAccelerate': 'cubic-bezier(0.3, 0.0, 0.8, 0.15)',
  'motion.easing.linear': 'cubic-bezier(0, 0, 1, 1)',

  // Motion — theme transition
  'motion.themeTransition.duration': '500ms',
  'motion.themeTransition.easing': 'cubic-bezier(0.2, 0.0, 0, 1.0)',

  // Responsive — typography scale factors
  'responsive.scale.medium.display': '1.10',
  'responsive.scale.medium.headline': '1.05',
  'responsive.scale.expanded.display': '1.20',
  'responsive.scale.expanded.headline': '1.10',
  'responsive.scale.expanded.title': '1.05',

  // Spacing (4px grid, 17 stops)
  'spacing.0': '0px',
  'spacing.1': '4px',
  'spacing.2': '8px',
  'spacing.3': '12px',
  'spacing.4': '16px',
  'spacing.5': '20px',
  'spacing.6': '24px',
  'spacing.8': '32px',
  'spacing.10': '40px',
  'spacing.12': '48px',
  'spacing.14': '56px',
  'spacing.16': '64px',
  'spacing.20': '80px',
  'spacing.24': '96px',
  'spacing.32': '128px',
  'spacing.40': '160px',
  'spacing.48': '192px',

  // Spacing — semantic (Tier 2)
  'spacing.inline.xs': '4px',
  'spacing.inline.sm': '8px',
  'spacing.inline.md': '16px',
  'spacing.inline.lg': '24px',
  'spacing.inline.xl': '32px',
  'spacing.stack.xs': '4px',
  'spacing.stack.sm': '8px',
  'spacing.stack.md': '16px',
  'spacing.stack.lg': '24px',
  'spacing.stack.xl': '32px',
  'spacing.inset.xs': '4px',
  'spacing.inset.sm': '8px',
  'spacing.inset.md': '16px',
  'spacing.inset.lg': '24px',
  'spacing.inset.xl': '32px',

  // Border Width
  'borderWidth.none': '0px',
  'borderWidth.thin': '1px',
  'borderWidth.medium': '2px',
  'borderWidth.thick': '4px',

  // Shape / Border Radius (new 9-stop scale)
  'shape.radius.none': '0dp',
  'shape.radius.xs': '2dp',
  'shape.radius.sm': '4dp',
  'shape.radius.md': '8dp',
  'shape.radius.lg': '12dp',
  'shape.radius.xl': '16dp',
  'shape.radius.xxl': '24dp',
  'shape.radius.xxxl': '28dp',
  'shape.radius.full': '9999dp',

  // Typography — extended styles
  'typography.displayExtraLarge.fontFamily': 'Roboto',
  'typography.displayExtraLarge.fontSize': '72sp',
  'typography.displayExtraLarge.fontWeight': '400',
  'typography.displayExtraLarge.lineHeight': '80sp',
  'typography.displayExtraLarge.letterSpacing': '-0.5sp',
  'typography.bodyExtraSmall.fontFamily': 'Roboto',
  'typography.bodyExtraSmall.fontSize': '10sp',
  'typography.bodyExtraSmall.fontWeight': '400',
  'typography.bodyExtraSmall.lineHeight': '14sp',
  'typography.bodyExtraSmall.letterSpacing': '0.4sp',

  // Motion — semantic durations
  'motion.duration.instant': '0ms',
  'motion.duration.fast': '100ms',
  'motion.duration.normal': '250ms',
  'motion.duration.slow': '400ms',
  'motion.duration.slower': '600ms',

  // Motion — delays
  'motion.delay.none': '0ms',
  'motion.delay.short': '100ms',

  // Motion — additional easings
  'motion.easing.bounce': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
}

const lightColors: ThemeTokenMap = {
  'color.primary': '#6750A4',
  'color.onPrimary': '#FFFFFF',
  'color.primaryContainer': '#EADDFF',
  'color.onPrimaryContainer': '#21005D',
  'color.secondary': '#625B71',
  'color.onSecondary': '#FFFFFF',
  'color.secondaryContainer': '#E8DEF8',
  'color.onSecondaryContainer': '#1D192B',
  'color.tertiary': '#7D5260',
  'color.onTertiary': '#FFFFFF',
  'color.tertiaryContainer': '#FFD8E4',
  'color.onTertiaryContainer': '#31111D',
  'color.error': '#B3261E',
  'color.onError': '#FFFFFF',
  'color.errorContainer': '#F9DEDC',
  'color.onErrorContainer': '#410E0B',
  'color.surface': '#FEF7FF',
  'color.onSurface': '#1D1B20',
  'color.surfaceVariant': '#E7E0EC',
  'color.onSurfaceVariant': '#49454F',
  'color.surfaceContainer': '#F3EDF7',
  'color.surfaceContainerHigh': '#ECE6F0',
  'color.surfaceContainerHighest': '#E6E0E9',
  'color.surfaceContainerLow': '#F7F2FA',
  'color.surfaceContainerLowest': '#FFFFFF',
  'color.background': '#FEF7FF',
  'color.onBackground': '#1D1B20',
  'color.outline': '#79747E',
  'color.outlineVariant': '#CAC4D0',
  'color.inverseSurface': '#322F35',
  'color.inverseOnSurface': '#F5EFF7',
  'color.inversePrimary': '#D0BCFF',
  'color.scrim': '#000000',
  'color.shadow': '#000000',

  // Shadow — light theme
  'shadow.elevation.none': 'none',
  'shadow.elevation.xs': '0 1px 2px 0 rgba(0,0,0,0.05)',
  'shadow.elevation.sm': '0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px -1px rgba(0,0,0,0.1)',
  'shadow.elevation.md': '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)',
  'shadow.elevation.lg': '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1)',
  'shadow.elevation.xl': '0 20px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.1)',
  'shadow.elevation.xxl': '0 25px 50px -12px rgba(0,0,0,0.25)',
  'shadow.subtle': '0 1px 2px 0 rgba(0,0,0,0.05)',
  'shadow.raised': '0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px -1px rgba(0,0,0,0.1)',
  'shadow.floating': '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1)',
  'shadow.overlay': '0 20px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.1)',
  'shadow.dramatic': '0 25px 50px -12px rgba(0,0,0,0.25)',
  'shadow.state.focus': '0 0 0 3px rgba(103,80,164,0.4)',
  'shadow.state.error': '0 0 0 3px rgba(179,38,30,0.4)',
  'shadow.state.active': '0 0 0 2px rgba(103,80,164,0.3)',
  'shadow.state.selected': '0 0 0 2px rgba(103,80,164,0.2)',

  // Color — Tier 2 semantic (light)
  'color.interactive.hover': '#5B4399',
  'color.interactive.pressed': '#4F378B',
  'color.interactive.disabled': '#1D1B2014',
  'color.interactive.focus': '#6750A4',
  'color.feedback.success': '#1B6D30',
  'color.feedback.successContainer': '#A8F5AC',
  'color.feedback.onSuccess': '#FFFFFF',
  'color.feedback.onSuccessContainer': '#002107',
  'color.feedback.warning': '#7C5800',
  'color.feedback.warningContainer': '#FFDEA1',
  'color.feedback.onWarning': '#FFFFFF',
  'color.feedback.onWarningContainer': '#271900',
  'color.feedback.info': '#0061A4',
  'color.feedback.infoContainer': '#D1E4FF',
  'color.feedback.onInfo': '#FFFFFF',
  'color.feedback.onInfoContainer': '#001D36',
  'color.text.primary': '#1D1B20',
  'color.text.secondary': '#49454F',
  'color.text.disabled': '#1D1B2061',
  'color.text.inverse': '#F5EFF7',
  'color.border.default': '#79747E',
  'color.border.strong': '#1D1B20',
  'color.border.subtle': '#CAC4D0',
  'color.border.disabled': '#1D1B2029',
}

const darkColors: ThemeTokenMap = {
  'color.primary': '#D0BCFF',
  'color.onPrimary': '#381E72',
  'color.primaryContainer': '#4F378B',
  'color.onPrimaryContainer': '#EADDFF',
  'color.secondary': '#CCC2DC',
  'color.onSecondary': '#332D41',
  'color.secondaryContainer': '#4A4458',
  'color.onSecondaryContainer': '#E8DEF8',
  'color.tertiary': '#EFB8C8',
  'color.onTertiary': '#492532',
  'color.tertiaryContainer': '#633B48',
  'color.onTertiaryContainer': '#FFD8E4',
  'color.error': '#F2B8B5',
  'color.onError': '#601410',
  'color.errorContainer': '#8C1D18',
  'color.onErrorContainer': '#F9DEDC',
  'color.surface': '#141218',
  'color.onSurface': '#E6E0E9',
  'color.surfaceVariant': '#49454F',
  'color.onSurfaceVariant': '#CAC4D0',
  'color.surfaceContainer': '#211F26',
  'color.surfaceContainerHigh': '#2B2930',
  'color.surfaceContainerHighest': '#36343B',
  'color.surfaceContainerLow': '#1D1B20',
  'color.surfaceContainerLowest': '#0F0D13',
  'color.background': '#141218',
  'color.onBackground': '#E6E0E9',
  'color.outline': '#938F99',
  'color.outlineVariant': '#49454F',
  'color.inverseSurface': '#E6E0E9',
  'color.inverseOnSurface': '#322F35',
  'color.inversePrimary': '#6750A4',
  'color.scrim': '#000000',
  'color.shadow': '#000000',

  // Shadow — dark theme (higher opacity)
  'shadow.elevation.none': 'none',
  'shadow.elevation.xs': '0 1px 2px 0 rgba(0,0,0,0.3)',
  'shadow.elevation.sm': '0 1px 3px 0 rgba(0,0,0,0.4), 0 1px 2px -1px rgba(0,0,0,0.3)',
  'shadow.elevation.md': '0 4px 6px -1px rgba(0,0,0,0.4), 0 2px 4px -2px rgba(0,0,0,0.3)',
  'shadow.elevation.lg': '0 10px 15px -3px rgba(0,0,0,0.4), 0 4px 6px -4px rgba(0,0,0,0.3)',
  'shadow.elevation.xl': '0 20px 25px -5px rgba(0,0,0,0.4), 0 8px 10px -6px rgba(0,0,0,0.3)',
  'shadow.elevation.xxl': '0 25px 50px -12px rgba(0,0,0,0.6)',
  'shadow.subtle': '0 1px 2px 0 rgba(0,0,0,0.3)',
  'shadow.raised': '0 1px 3px 0 rgba(0,0,0,0.4), 0 1px 2px -1px rgba(0,0,0,0.3)',
  'shadow.floating': '0 10px 15px -3px rgba(0,0,0,0.4), 0 4px 6px -4px rgba(0,0,0,0.3)',
  'shadow.overlay': '0 20px 25px -5px rgba(0,0,0,0.4), 0 8px 10px -6px rgba(0,0,0,0.3)',
  'shadow.dramatic': '0 25px 50px -12px rgba(0,0,0,0.6)',
  'shadow.state.focus': '0 0 0 3px rgba(208,188,255,0.4)',
  'shadow.state.error': '0 0 0 3px rgba(242,184,181,0.4)',
  'shadow.state.active': '0 0 0 2px rgba(208,188,255,0.3)',
  'shadow.state.selected': '0 0 0 2px rgba(208,188,255,0.2)',

  // Color — Tier 2 semantic (dark)
  'color.interactive.hover': '#E0D0FF',
  'color.interactive.pressed': '#EADDFF',
  'color.interactive.disabled': '#E6E0E914',
  'color.interactive.focus': '#D0BCFF',
  'color.feedback.success': '#6EDB75',
  'color.feedback.successContainer': '#005313',
  'color.feedback.onSuccess': '#003909',
  'color.feedback.onSuccessContainer': '#A8F5AC',
  'color.feedback.warning': '#F5C63D',
  'color.feedback.warningContainer': '#5C4000',
  'color.feedback.onWarning': '#412D00',
  'color.feedback.onWarningContainer': '#FFDEA1',
  'color.feedback.info': '#9ECAFF',
  'color.feedback.infoContainer': '#003258',
  'color.feedback.onInfo': '#003258',
  'color.feedback.onInfoContainer': '#D1E4FF',
  'color.text.primary': '#E6E0E9',
  'color.text.secondary': '#CAC4D0',
  'color.text.disabled': '#E6E0E961',
  'color.text.inverse': '#322F35',
  'color.border.default': '#938F99',
  'color.border.strong': '#E6E0E9',
  'color.border.subtle': '#49454F',
  'color.border.disabled': '#E6E0E929',
}

/** Get the full M3 baseline token set for a given variant */
export function getSystemDefaults(variant: ThemeVariant): ThemeTokenMap {
  const colors = variant === 'dark' ? darkColors : lightColors
  return { ...sharedTokens, ...colors }
}
