org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.workers.max=4
kotlin.incremental=true
kotlin.stdlib.default.dependency=true
kotlin.ignore.tcsm.overflow=true
kotlin.version=2.4.20
metro.generateContributionProviders=true
kotlinLanguageVersion=2.4
kotlin.code.style=official
kotlin.compiler.execution.strategy=daemon
systemProp.kmp.targets=jvm
kotlin.mpp.enableCInteropCommonization=true
android.useAndroidX=true
android.nonTransitiveRClass=true
ksp.useKSP2=true
kotlin.native.enableKlibsCrossCompilation=false
kotlin.js.yarn=false
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
kotlinx.atomicfu.enableJvmIrTransformation=true
kotlin.incremental.js=false
kotlin.incremental.js.klib=false
kotlin.native.ignoreDisabledTargets=true
idk.consumeCoreAsArtifacts=true
idk.consumePlatformAsArtifacts=true