/*
 * © 2026 Sphereon International B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sphereon.crypto.kms.rest.server.controller

import com.sphereon.core.api.conf.DefaultPrincipalMapPropertySource
import com.sphereon.crypto.kms.rest.server.TestApiAppGraph
import com.sphereon.crypto.kms.rest.server.createTestApiAppGraph
import com.sphereon.ktor.server.inject.KotlinInjectPlugin
import com.sphereon.ktor.server.inject.installUniversalHttpAdapters
import io.ktor.client.HttpClient
import io.ktor.client.request.accept
import io.ktor.client.request.delete
import io.ktor.client.request.get
import io.ktor.client.request.header
import io.ktor.client.request.post
import io.ktor.client.request.setBody
import io.ktor.client.statement.bodyAsText
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.http.contentType
import io.ktor.server.application.install
import io.ktor.server.cio.CIO
import io.ktor.server.cio.CIOApplicationEngine
import io.ktor.server.engine.EmbeddedServer
import io.ktor.server.engine.embeddedServer
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.test.runTest
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.net.ServerSocket
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Integration test demonstrating multi-tenant KMS key isolation via REST API.
 *
 * This test verifies that keys are isolated between tenants at the session/context level:
 * 1. Both tenants can generate keys in the same shared provider
 * 2. Keys generated by tenant A are NOT visible to tenant B and vice versa
 * 3. Same alias can exist independently for different tenants
 * 4. Cross-tenant key retrieval returns not-found
 * 5. Cross-tenant key deletion is prevented
 * 6. Key deletion only affects the owning tenant's keys
 */
class MultiTenantKmsIsolationTest {
    private lateinit var appGraph: TestApiAppGraph
    private lateinit var server: EmbeddedServer<CIOApplicationEngine, CIOApplicationEngine.Configuration>
    private lateinit var client: HttpClient
    private var port: Int = 0

    @BeforeEach
    fun setUp() {
        port = ServerSocket(0).use { it.localPort }

        DefaultPrincipalMapPropertySource.addProperties(
            mapOf(
                "$PROPERTY_PREFIX.type" to "software",
                "$PROPERTY_PREFIX.id" to SHARED_PROVIDER,
                "$PROPERTY_PREFIX.persistKeysDuringGeneration" to "true",
                "$PROPERTY_PREFIX.exposePrivateKeysDuringGeneration" to "true",
                "$PROPERTY_PREFIX.keyStore.type" to "memory",
                "$PROPERTY_PREFIX.keyStore.id" to "test-memory-keystore",
                "$PROPERTY_PREFIX.keyStore.keyVisibility" to "private",
                "$PROPERTY_PREFIX.keyStore.overwriteAlias" to "true",
            ),
        )

        appGraph =
            createTestApiAppGraph(
                application = Unit,
                appId = "kms-multitenant-test",
                profile = "test",
                version = "1.0.0",
            )
        appGraph.userContextManager.destroyAll()

        server =
            embeddedServer(CIO, port = port) {
                install(KotlinInjectPlugin) {
                    this.appGraph = this@MultiTenantKmsIsolationTest.appGraph
                }
                installUniversalHttpAdapters {
                    verboseLogging = true
                }
            }
        server.start(wait = false)
        runBlocking { delay(500) }

        client = HttpClient(io.ktor.client.engine.cio.CIO)
    }

    @AfterEach
    fun tearDown() {
        client.close()
        server.stop(1000, 2000)
        DefaultPrincipalMapPropertySource.deleteProperty("$PROPERTY_PREFIX.type")
        DefaultPrincipalMapPropertySource.deleteProperty("$PROPERTY_PREFIX.id")
        DefaultPrincipalMapPropertySource.deleteProperty("$PROPERTY_PREFIX.persistKeysDuringGeneration")
        DefaultPrincipalMapPropertySource.deleteProperty("$PROPERTY_PREFIX.exposePrivateKeysDuringGeneration")
        DefaultPrincipalMapPropertySource.deleteProperty("$PROPERTY_PREFIX.keyStore.type")
        DefaultPrincipalMapPropertySource.deleteProperty("$PROPERTY_PREFIX.keyStore.id")
        DefaultPrincipalMapPropertySource.deleteProperty("$PROPERTY_PREFIX.keyStore.keyVisibility")
        DefaultPrincipalMapPropertySource.deleteProperty("$PROPERTY_PREFIX.keyStore.overwriteAlias")
    }

    // ========================================
    // Key Generation Tests - Shared Provider
    // ========================================

    @Test
    fun tenantACanGenerateKeyInSharedProvider() =
        runTest {
            val response = generateKey(TENANT_A_ID, TENANT_A_USER, "tenant-a-key-in-shared")
            assertEquals(HttpStatusCode.Created, response.status)

            val body = Json.parseToJsonElement(response.bodyAsText()).jsonObject
            assertEquals("tenant-a-key-in-shared", body["keyPair"]!!.jsonObject["alias"]!!.jsonPrimitive.content)
        }

    @Test
    fun tenantBCanGenerateKeyInSharedProvider() =
        runTest {
            val response = generateKey(TENANT_B_ID, TENANT_B_USER, "tenant-b-key-in-shared")
            assertEquals(HttpStatusCode.Created, response.status)

            val body = Json.parseToJsonElement(response.bodyAsText()).jsonObject
            assertEquals("tenant-b-key-in-shared", body["keyPair"]!!.jsonObject["alias"]!!.jsonPrimitive.content)
        }

    // ========================================
    // Key Isolation Tests - Shared Provider
    // ========================================

    @Test
    fun tenantsHaveIsolatedKeysInSharedProvider() =
        runTest {
            // Tenant A generates a key with alias "isolation-test-key"
            val resultA = generateKey(TENANT_A_ID, TENANT_A_USER, "isolation-test-key", alg = "ECDSA_SHA256")
            assertEquals(HttpStatusCode.Created, resultA.status)

            // Tenant B generates a key with the SAME alias
            val resultB = generateKey(TENANT_B_ID, TENANT_B_USER, "isolation-test-key", alg = "ECDSA_SHA384")
            assertEquals(HttpStatusCode.Created, resultB.status)

            // List keys for Tenant A
            val listA = listKeys(TENANT_A_ID, TENANT_A_USER)
            assertEquals(HttpStatusCode.OK, listA.status)
            val keysA = Json.parseToJsonElement(listA.bodyAsText()).jsonObject["keyInfos"]!!.jsonArray
            val aliasesA = keysA.map { it.jsonObject["alias"]!!.jsonPrimitive.content }
            assertTrue(aliasesA.contains("isolation-test-key"), "Tenant A should see its own key")

            // List keys for Tenant B
            val listB = listKeys(TENANT_B_ID, TENANT_B_USER)
            assertEquals(HttpStatusCode.OK, listB.status)
            val keysB = Json.parseToJsonElement(listB.bodyAsText()).jsonObject["keyInfos"]!!.jsonArray
            val aliasesB = keysB.map { it.jsonObject["alias"]!!.jsonPrimitive.content }
            assertTrue(aliasesB.contains("isolation-test-key"), "Tenant B should see its own key")

            // Verify keys are different by comparing KIDs
            val kidA =
                keysA
                    .last()
                    .jsonObject["kid"]!!
                    .jsonPrimitive.content
            val kidB =
                keysB
                    .last()
                    .jsonObject["kid"]!!
                    .jsonPrimitive.content
            assertTrue(kidA != kidB, "Keys should have different KIDs despite same alias")
        }

    // ========================================
    // Key Retrieval Tests
    // ========================================

    @Test
    fun tenantCanRetrieveOwnKeyFromSharedProvider() =
        runTest {
            // Generate a key
            val genResponse = generateKey(TENANT_A_ID, TENANT_A_USER, "retrieve-test-a")
            assertEquals(HttpStatusCode.Created, genResponse.status)

            val kid =
                Json
                    .parseToJsonElement(genResponse.bodyAsText())
                    .jsonObject["keyPair"]!!
                    .jsonObject["kid"]!!
                    .jsonPrimitive.content

            // Retrieve the key
            val getResponse =
                client.get("http://localhost:$port/keys/$kid") {
                    header("X-Tenant-ID", TENANT_A_ID)
                    header("X-User-ID", TENANT_A_USER)
                    accept(ContentType.Application.Json)
                }
            assertEquals(HttpStatusCode.OK, getResponse.status)

            val body = Json.parseToJsonElement(getResponse.bodyAsText()).jsonObject
            assertEquals("retrieve-test-a", body["keyInfo"]!!.jsonObject["alias"]!!.jsonPrimitive.content)
        }

    @Test
    fun tenantBCannotRetrieveTenantAKeyFromSharedProvider() =
        runTest {
            // Tenant A generates a key
            val genResponse = generateKey(TENANT_A_ID, TENANT_A_USER, "cross-tenant-test")
            assertEquals(HttpStatusCode.Created, genResponse.status)

            val kid =
                Json
                    .parseToJsonElement(genResponse.bodyAsText())
                    .jsonObject["keyPair"]!!
                    .jsonObject["kid"]!!
                    .jsonPrimitive.content

            // Tenant B attempts to retrieve it
            val getResponse =
                client.get("http://localhost:$port/keys/$kid") {
                    header("X-Tenant-ID", TENANT_B_ID)
                    header("X-User-ID", TENANT_B_USER)
                    accept(ContentType.Application.Json)
                }
            // Should not find the key (belongs to tenant A)
            assertTrue(
                getResponse.status == HttpStatusCode.NotFound || getResponse.status == HttpStatusCode.BadRequest,
                "Cross-tenant key retrieval should fail, got ${getResponse.status}",
            )
        }

    // ========================================
    // Key Deletion Tests
    // ========================================

    @Test
    fun tenantCanDeleteOwnKeyFromSharedProvider() =
        runTest {
            // Generate a key
            val genResponse = generateKey(TENANT_A_ID, TENANT_A_USER, "delete-test-a")
            assertEquals(HttpStatusCode.Created, genResponse.status)

            val kid =
                Json
                    .parseToJsonElement(genResponse.bodyAsText())
                    .jsonObject["keyPair"]!!
                    .jsonObject["kid"]!!
                    .jsonPrimitive.content

            // Delete the key
            val deleteResponse =
                client.delete("http://localhost:$port/keys/$kid") {
                    header("X-Tenant-ID", TENANT_A_ID)
                    header("X-User-ID", TENANT_A_USER)
                }
            assertEquals(HttpStatusCode.NoContent, deleteResponse.status)

            // Verify key is deleted
            val getResponse =
                client.get("http://localhost:$port/keys/$kid") {
                    header("X-Tenant-ID", TENANT_A_ID)
                    header("X-User-ID", TENANT_A_USER)
                    accept(ContentType.Application.Json)
                }
            assertTrue(
                getResponse.status == HttpStatusCode.NotFound || getResponse.status == HttpStatusCode.BadRequest,
                "Deleted key should not be found",
            )
        }

    @Test
    fun tenantBCannotDeleteTenantAKeyFromSharedProvider() =
        runTest {
            // Tenant A generates a key
            val genResponse = generateKey(TENANT_A_ID, TENANT_A_USER, "protected-key-a")
            assertEquals(HttpStatusCode.Created, genResponse.status)

            val kid =
                Json
                    .parseToJsonElement(genResponse.bodyAsText())
                    .jsonObject["keyPair"]!!
                    .jsonObject["kid"]!!
                    .jsonPrimitive.content

            // Tenant B attempts to delete it
            val deleteResponse =
                client.delete("http://localhost:$port/keys/$kid") {
                    header("X-Tenant-ID", TENANT_B_ID)
                    header("X-User-ID", TENANT_B_USER)
                }
            // Should fail (not found for tenant B)
            assertTrue(
                deleteResponse.status == HttpStatusCode.NotFound || deleteResponse.status == HttpStatusCode.BadRequest,
                "Cross-tenant key deletion should fail, got ${deleteResponse.status}",
            )

            // Verify tenant A's key still exists
            val getResponse =
                client.get("http://localhost:$port/keys/$kid") {
                    header("X-Tenant-ID", TENANT_A_ID)
                    header("X-User-ID", TENANT_A_USER)
                    accept(ContentType.Application.Json)
                }
            assertEquals(HttpStatusCode.OK, getResponse.status, "Tenant A's key should still exist after failed cross-tenant delete")
        }

    // ========================================
    // Comprehensive Integration Test
    // ========================================

    @Test
    fun comprehensiveMultiTenantKeyIsolationScenario() =
        runTest {
            // Tenant A generates key in shared provider
            val resultAShared = generateKey(TENANT_A_ID, TENANT_A_USER, "comprehensive-a")
            assertEquals(HttpStatusCode.Created, resultAShared.status)

            // Tenant B generates key in shared provider
            val resultBShared = generateKey(TENANT_B_ID, TENANT_B_USER, "comprehensive-b")
            assertEquals(HttpStatusCode.Created, resultBShared.status)

            // Verify Tenant A only sees its own key
            val listA = listKeys(TENANT_A_ID, TENANT_A_USER)
            assertEquals(HttpStatusCode.OK, listA.status)
            val aliasesA =
                Json
                    .parseToJsonElement(listA.bodyAsText())
                    .jsonObject["keyInfos"]!!
                    .jsonArray
                    .map { it.jsonObject["alias"]!!.jsonPrimitive.content }
            assertTrue(aliasesA.contains("comprehensive-a"), "Tenant A should see its own key")
            assertTrue(!aliasesA.contains("comprehensive-b"), "Tenant A should NOT see tenant B's key")

            // Verify Tenant B only sees its own key
            val listB = listKeys(TENANT_B_ID, TENANT_B_USER)
            assertEquals(HttpStatusCode.OK, listB.status)
            val aliasesB =
                Json
                    .parseToJsonElement(listB.bodyAsText())
                    .jsonObject["keyInfos"]!!
                    .jsonArray
                    .map { it.jsonObject["alias"]!!.jsonPrimitive.content }
            assertTrue(aliasesB.contains("comprehensive-b"), "Tenant B should see its own key")
            assertTrue(!aliasesB.contains("comprehensive-a"), "Tenant B should NOT see tenant A's key")
        }

    // ========================================
    // Helpers
    // ========================================

    private suspend fun generateKey(
        tenantId: String,
        userId: String,
        alias: String,
        alg: String = "ECDSA_SHA256",
    ): io.ktor.client.statement.HttpResponse {
        val payload =
            """
            {
                "alias": "$alias",
                "use": "sig",
                "alg": "$alg",
                "keyOperations": ["sign"]
            }
            """.trimIndent()

        return client.post("http://localhost:$port/keys/generate") {
            header("X-Tenant-ID", tenantId)
            header("X-User-ID", userId)
            contentType(ContentType.Application.Json)
            setBody(payload)
        }
    }

    private suspend fun listKeys(
        tenantId: String,
        userId: String,
    ): io.ktor.client.statement.HttpResponse =
        client.get("http://localhost:$port/keys") {
            header("X-Tenant-ID", tenantId)
            header("X-User-ID", userId)
            accept(ContentType.Application.Json)
        }

    companion object {
        const val TENANT_A_ID = "tenant-a"
        const val TENANT_A_USER = "user-a"
        const val TENANT_B_ID = "tenant-b"
        const val TENANT_B_USER = "user-b"
        const val SHARED_PROVIDER = "testsoftware"
        private const val PROPERTY_PREFIX = "kms.providers.testsoftware"
    }
}
