/*
 * © 2026 Sphereon International B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.sphereon.did.manager.impl

import com.sphereon.core.api.conf.DefaultPrincipalMapPropertySource
import com.sphereon.crypto.core.generic.Curve
import com.sphereon.crypto.core.generic.KeyTypeMapping
import com.sphereon.crypto.core.jose.JwaCurve
import com.sphereon.crypto.core.jose.JwaKeyType
import com.sphereon.crypto.core.jose.Jwk
import com.sphereon.did.manager.DidManager
import com.sphereon.did.manager.impl.testutil.DidManagerTestContext
import com.sphereon.did.manager.impl.testutil.createDidManagerTestAppGraph
import com.sphereon.did.models.VerificationPurpose
import kotlinx.coroutines.test.runTest
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * E2E integration tests for DID Creation DSL with full DI stack.
 *
 * These tests verify the complete flow:
 * 1. DSL configuration
 * 2. Key generation via KMS (software provider)
 * 3. DID creation via method providers (did:key, did:jwk)
 * 4. Persistence via DidRepository (in-memory)
 */
class DidCreationDslE2ETest {
    private lateinit var app: com.sphereon.di.app.AppGraph
    private lateinit var dslProcessor: DidCreationDslProcessor
    private lateinit var didManager: DidManager

    @AfterTest
    fun tearDown() {
        if (::app.isInitialized) {
            app.userContextManager.destroyAll()
        }
    }

    @BeforeTest
    fun setUp() {
        // Configure the software KMS provider via properties
        DefaultPrincipalMapPropertySource.addProperties(
            mapOf(
                "kms.providers.softwaretest.type" to "software",
                "kms.providers.softwaretest.id" to "softwaretest",
                "kms.providers.softwaretest.keystore.type" to "memory",
                "kms.providers.softwaretest.keystore.id" to "test-memory-keystore",
                "kms.providers.softwaretest.keystore.keyVisibility" to "private",
                "kms.providers.softwaretest.keystore.overwriteAlias" to "true",
            ),
        )

        // Create the full graph hierarchy via DI
        app = createDidManagerTestAppGraph(testInstance = this)

        // Destroy any existing contexts to ensure config is re-read
        app.userContextManager.destroyAll()

        val userContext = app.userContextManager.getAnonymous()
        val session = userContext.sessionContextManager.createOrGetFromId("dsl-e2e-test", principalType = com.sphereon.di.context.PrincipalType.USER)

        val sessionGraph = session.graph

        // Access via the Graph interfaces contributed by the impl classes via @ContributesTo
        dslProcessor = (sessionGraph as DidCreationDslProcessorImpl.Graph).didCreationDslProcessor
        didManager = (sessionGraph as DidManagerServiceImpl.Graph).didManager
    }

    // ==================== did:key Creation Tests ====================

    @Test
    fun testCreateDidKeyWithAutoGeneratedP256Key() =
        runTest {
            // Note: Using P-256 (EC) instead of Ed25519 (OKP) because the software KMS provider
            // doesn't support Ed25519/EdDSA curves - only ECDSA curves (P-256, P-384, P-521)
            val result =
                dslProcessor.create {
                    method("key")
                    alias("test-p256-did-key")
                    autoGenerateKey {
                        keyType(KeyTypeMapping.EC)
                        curve(Curve.P_256)
                        kmsProvider("softwaretest")
                        purposes(VerificationPurpose.AUTHENTICATION, VerificationPurpose.ASSERTION_METHOD)
                    }
                }

            assertTrue(result.isOk, "DID creation should succeed: ${result.getErrorOrNull()}")
            val managedDid = result.getOrThrow()

            // Verify DID was created with P-256 (zDn... prefix for P-256 multicodec)
            assertNotNull(managedDid.did, "DID should be set")
            assertTrue(managedDid.did.startsWith("did:key:zDn"), "Should be a did:key with P-256")
            assertEquals("test-p256-did-key", managedDid.alias, "Alias should match")

            // Verify DID document
            val document = managedDid.document
            assertNotNull(document, "DID document should be present")
            assertEquals(managedDid.did, document.id, "DID document ID should match")

            // Verify verification methods
            val verificationMethods = document.verificationMethod
            assertNotNull(verificationMethods, "Verification methods should be present")
            assertTrue(verificationMethods.isNotEmpty(), "Should have at least one verification method")

            // Verify persistence via DidManager
            val persisted = didManager.get(managedDid.did).getOrThrow()
            assertNotNull(persisted, "DID should be retrievable")
            assertEquals(managedDid.did, persisted.did, "Retrieved DID should match")
            assertEquals("test-p256-did-key", persisted.alias, "Retrieved alias should match")
        }

    @Test
    fun testCreateDidKeyWithAutoGeneratedP384Key() =
        runTest {
            // Test with a different curve to ensure flexibility
            val result =
                dslProcessor.create {
                    method("key")
                    alias("test-p384-did")
                    autoGenerateKey {
                        keyType(KeyTypeMapping.EC)
                        curve(Curve.P_384)
                        kmsProvider("softwaretest")
                        purposes(VerificationPurpose.AUTHENTICATION)
                    }
                }

            assertTrue(result.isOk, "DID creation should succeed: ${result.getErrorOrNull()}")
            val managedDid = result.getOrThrow()

            // Verify DID was created (P-384 uses different multicodec prefix)
            assertNotNull(managedDid.did, "DID should be set")
            assertTrue(managedDid.did.startsWith("did:key:"), "Should be a did:key")

            // Verify persistence via DidManager
            val persisted = didManager.get(managedDid.did).getOrThrow()
            assertNotNull(persisted, "DID should be retrievable")
        }

    // ==================== did:jwk Creation Tests ====================

    @Test
    fun testCreateDidJwkWithExistingJwk() =
        runTest {
            val jwk =
                Jwk(
                    kty = JwaKeyType.OKP,
                    crv = JwaCurve.Ed25519,
                    x = "Q__LMeuER6M24T4DDbGAI6hLYgmqJJPvcT_87r4YWqs",
                )

            val result =
                dslProcessor.create {
                    method("jwk")
                    alias("test-existing-jwk-did")
                    useExistingKey(jwk)
                }

            assertTrue(result.isOk, "DID creation should succeed: ${result.getErrorOrNull()}")
            val managedDid = result.getOrThrow()

            // Verify DID was created
            assertNotNull(managedDid.did, "DID should be set")
            assertTrue(managedDid.did.startsWith("did:jwk:"), "Should be a did:jwk")
            assertEquals("test-existing-jwk-did", managedDid.alias, "Alias should match")

            // Verify persistence via DidManager
            val persisted = didManager.get(managedDid.did).getOrThrow()
            assertNotNull(persisted, "DID should be retrievable")
        }

    @Test
    fun testCreateDidJwkWithAutoGeneratedKey() =
        runTest {
            val result =
                dslProcessor.create {
                    method("jwk")
                    alias("test-auto-jwk-did")
                    autoGenerateKey {
                        keyType(KeyTypeMapping.EC)
                        curve(Curve.P_256)
                        kmsProvider("softwaretest")
                    }
                }

            assertTrue(result.isOk, "DID creation should succeed: ${result.getErrorOrNull()}")
            val managedDid = result.getOrThrow()

            // Verify DID was created
            assertNotNull(managedDid.did, "DID should be set")
            assertTrue(managedDid.did.startsWith("did:jwk:"), "Should be a did:jwk")

            // Verify persistence via DidManager
            val persisted = didManager.get(managedDid.did).getOrThrow()
            assertNotNull(persisted, "DID should be retrievable")
        }

    // ==================== Key Mapping Tests ====================

    @Test
    fun testCreateDidWithKeyMappingPersisted() =
        runTest {
            val result =
                dslProcessor.create {
                    method("key")
                    alias("test-key-mapping-did")
                    autoGenerateKey {
                        keyType(KeyTypeMapping.EC)
                        curve(Curve.P_256)
                        kmsProvider("softwaretest")
                        purposes(VerificationPurpose.AUTHENTICATION)
                    }
                }

            assertTrue(result.isOk, "DID creation should succeed: ${result.getErrorOrNull()}")
            val managedDid = result.getOrThrow()

            // Verify key mappings are present in the result
            assertTrue(managedDid.keys.isNotEmpty(), "Key mappings should be present in result")

            // Verify key mapping contains correct information
            val keyMapping = managedDid.keys.first()
            assertNotNull(keyMapping.kmsKeyAlias, "KMS key alias should be set")
            assertNotNull(keyMapping.kmsProviderId, "KMS provider ID should be set")

            // Verify persistence via DidManager
            val persisted = didManager.get(managedDid.did).getOrThrow()
            assertTrue(persisted.keys.isNotEmpty(), "Key mappings should be persisted")
        }

    // ==================== Error Cases ====================

    @Test
    fun testCreateDidWithUnsupportedMethodFails() =
        runTest {
            val result =
                dslProcessor.create {
                    method("unsupported")
                    autoGenerateKey {
                        keyType(KeyTypeMapping.EC)
                        curve(Curve.P_256)
                        kmsProvider("softwaretest")
                    }
                }

            assertTrue(result.isErr, "Creation with unsupported method should fail")
        }

    @Test
    fun testCreateDidWithMissingMethodFails() =
        runTest {
            // Test that DID creation fails when no method is specified
            // The DSL builder throws IllegalStateException when method is not set
            val exception =
                try {
                    dslProcessor.create {
                        // No method() call - should fail
                        autoGenerateKey {
                            keyType(KeyTypeMapping.EC)
                            curve(Curve.P_256)
                            kmsProvider("softwaretest")
                        }
                    }
                    null // If no exception, return null
                } catch (e: IllegalStateException) {
                    e
                }

            // Creation should fail because no method was specified
            assertNotNull(exception, "Creation without method should throw IllegalStateException")
            assertTrue(exception.message?.contains("method") == true, "Exception should mention missing method")
        }

    // ==================== Multiple DIDs Test ====================

    @Test
    fun testCreateMultipleDidsPersisted() =
        runTest {
            // Create first DID
            val result1 =
                dslProcessor.create {
                    method("key")
                    alias("multi-test-did-1")
                    autoGenerateKey {
                        keyType(KeyTypeMapping.EC)
                        curve(Curve.P_256)
                        kmsProvider("softwaretest")
                    }
                }
            assertTrue(result1.isOk, "First DID creation should succeed: ${result1.getErrorOrNull()}")

            // Create second DID
            val result2 =
                dslProcessor.create {
                    method("key")
                    alias("multi-test-did-2")
                    autoGenerateKey {
                        keyType(KeyTypeMapping.EC)
                        curve(Curve.P_256)
                        kmsProvider("softwaretest")
                    }
                }
            assertTrue(result2.isOk, "Second DID creation should succeed: ${result2.getErrorOrNull()}")

            // Verify both are persisted and distinct
            val did1 = result1.getOrThrow()
            val did2 = result2.getOrThrow()

            assertTrue(did1.did != did2.did, "DIDs should be different")

            // Verify both can be retrieved
            val persisted1 = didManager.get(did1.did).getOrThrow()
            val persisted2 = didManager.get(did2.did).getOrThrow()

            assertNotNull(persisted1, "First DID should be retrievable")
            assertNotNull(persisted2, "Second DID should be retrievable")
            assertEquals("multi-test-did-1", persisted1.alias)
            assertEquals("multi-test-did-2", persisted2.alias)

            // Verify find by alias works
            val foundByAlias = didManager.getByAlias("multi-test-did-1").getOrThrow()
            assertNotNull(foundByAlias, "Should find DID by alias")
            assertEquals(did1.did, foundByAlias.did)
        }
}
