/*
 * (c) 2026 Sphereon International B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 */

package com.sphereon.openid.oid4vci.integration

import com.sphereon.core.api.IdkResult
import com.sphereon.core.api.decodeFromBase64Url
import com.sphereon.core.api.encodeToBase64Url
import com.sphereon.crypto.core.KeyVisibility
import com.sphereon.crypto.core.ManagedKeyInfoType
import com.sphereon.crypto.core.generic.SignatureAlgorithm
import com.sphereon.crypto.core.jose.Jwk
import com.sphereon.crypto.core.jose.JwkUse
import com.sphereon.crypto.core.kms.KeyManagerService
import com.sphereon.crypto.core.kms.asKeyManagerServiceGraph
import com.sphereon.crypto.resolution.IdentifierService
import com.sphereon.crypto.resolution.extern.ExternalIdentifierJwkOpts
import com.sphereon.crypto.resolution.extern.ExternalIdentifierResult
import com.sphereon.di.session.SessionScope
import com.sphereon.openid.oid4vc.common.CredentialFormat
import com.sphereon.openid.oid4vci.common.model.CredentialConfigurationSupported
import com.sphereon.openid.oid4vci.common.model.CredentialDefinition
import com.sphereon.openid.oid4vci.common.model.CredentialRequest
import com.sphereon.openid.oid4vci.issuer.format.IssuanceContext
import com.sphereon.openid.oid4vci.issuer.format.SigningKeyMode
import com.sphereon.openid.oid4vci.issuer.format.CredentialFormatHandler
import com.sphereon.openid.oid4vci.issuer.impl.format.JwtVcJsonFormatHandler
import com.sphereon.openid.oid4vci.issuer.impl.format.VcLdJsonJwtFormatHandler
import com.sphereon.openid.oid4vp.common.ClientIdScheme
import com.sphereon.openid.oid4vp.common.ClientMetadata
import com.sphereon.openid.oid4vp.common.ResponseMode
import com.sphereon.openid.oid4vp.common.VpToken
import com.sphereon.openid.oid4vp.common.vpToken
import com.sphereon.openid.oid4vp.common.jwtVcFormatInfo
import com.sphereon.openid.oid4vp.dcql.DcqlCredentialQuery
import com.sphereon.openid.oid4vp.dcql.DcqlQuery
import com.sphereon.openid.oid4vp.dcql.w3cVcMeta
import com.sphereon.openid.oid4vp.holder.CreateAuthorizationResponseArgs
import com.sphereon.openid.oid4vp.holder.HolderJwtVpSigningIdentifier
import com.sphereon.openid.oid4vp.holder.Oid4vpHolder
import com.sphereon.openid.oid4vp.holder.ResolvedOid4vpRequest
import com.sphereon.openid.oid4vp.holder.SelectedCredential
import com.sphereon.openid.oid4vp.verifier.CreateAuthorizationRequestArgs
import com.sphereon.openid.oid4vp.verifier.Oid4vpVerifierService
import com.sphereon.openid.oid4vp.verifier.ParseAuthorizationResponseArgs
import com.sphereon.openid.oid4vp.verifier.TrustedAuthenticationResolution
import com.sphereon.openid.oid4vp.verifier.ValidateAuthorizationResponseArgs
import com.sphereon.openid.oid4vp.holder.VerifierInfo
import com.sphereon.oauth2.common.model.AuthorizationRequest
import com.sphereon.oauth2.common.model.AuthorizationResponse
import com.sphereon.wallet.unit.SecureComponentUsage
import dev.zacsweers.metro.ContributesTo
import kotlinx.coroutines.test.runTest
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertIs
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/** Production issuer, holder, verifier, and canonical identifier-resolution services. */
@ContributesTo(SessionScope::class)
interface VcdmConfiguredInlineJwkTestGraph {
    val jwtVcJsonFormatHandler: JwtVcJsonFormatHandler
    val vcLdJsonJwtFormatHandler: VcLdJsonJwtFormatHandler
    val oid4vpHolder: Oid4vpHolder
    val oid4vpVerifierService: Oid4vpVerifierService
    val identifierService: IdentifierService
}

/**
 * VCDM 1.1 and 2.0 JWT VC issue -> JWT VP presentation -> verification with explicitly configured JWKs.
 *
 * Issuer material is generated by the production software KMS; holder material is provisioned and
 * used only through the production WSCA. Trust is admitted as ExternalIdentifierJwkOpts and
 * resolved by the production IdentifierService; no verifier input is a prebuilt trusted JWKS and
 * no token-provided JWK can become an issuer or holder trust root.
 */
class VcdmJwtConfiguredInlineJwkE2ETest {
    private val ctx = Oid4vciTestContext(this)
    private val json = Json { ignoreUnknownKeys = true }
    private val issuer = "https://configured-jwk-vcdm-issuer.example"
    private val verifier = "https://configured-jwk-vcdm-verifier.example"
    private val holder = "https://configured-jwk-vcdm-holder.example"

    @Test
    fun vcdm11AndVcdm20IssuePresentAndVerifyUsesConfiguredInlineJwksForBothSignatures() =
        runTest {
            for (version in JwtVersion.entries) {
                val flow = createFlow("configured-jwk-valid-${version.name.lowercase()}", version)
                val issuerJwk = publicJwk(flow.issuerKey, issuerJwtKid(flow.credential))
                val holderJwk = flow.holderKey.publicJwk
                val issuerTrust = admit(issuer, issuerJwk)
                val holderTrust = admit(holder, holderJwk)

                val validation = validate(flow, issuerTrust, holderTrust)
                assertTrue(validation.isOk, "production verifier must return a structured result")
                assertTrue(validation.value.valid, "configured issuer and holder JWK signatures must verify: ${validation.value.errors}")

                val vp = assertNotNull(flow.response.value.vpToken!!.getSinglePresentation(QUERY_ID))
                assertCredentialShape(flow.credential, version)
                assertVpShape(vp, version)
                assertTrue(verifyRawJws(flow.credential, flow.issuerKey), "issuer VC signature must verify with its KMS public key")
                assertEquals(1, flow.response.value.vpToken!!.presentationCount)
                assertFalse(jwtHeader(flow.credential).containsKey("jwk"))
                assertFalse(jwtHeader(vp).containsKey("jwk"))
            }
        }

    @Test
    fun tokenControlledInlineJwkCannotReplaceConfiguredIssuerTrust() =
        runTest {
            val flow =
                createFlow("configured-jwk-token-controlled") { credential ->
                    val attackerKey = generateKey("configured-jwk-token-attacker")
                    addEmbeddedJwk(credential, publicJwk(attackerKey, "attacker-kid"))
                }
            val issuerTrust = admit(issuer, publicJwk(flow.issuerKey, issuerJwtKid(flow.credential)))
            val holderTrust = admit(holder, flow.holderKey.publicJwk)

            val validation = validate(flow, issuerTrust, holderTrust)
            assertTrue(validation.isOk, "token-controlled JWK validation should return a result: ${if (validation.isErr) validation.error else ""}")
            assertFalse(validation.value.valid, "an inline token JWK must never establish issuer trust")
            assertTrue(validation.value.errors.any { it.contains("embedded jwk") }, validation.value.errors.toString())
        }

    @Test
    fun wrongConfiguredIssuerJwkFailsCryptographicVerification() =
        runTest {
            val flow = createFlow("configured-jwk-wrong-key")
            val unrelatedKey = generateKey("configured-jwk-unrelated")
            val wrongIssuerTrust = admit(issuer, publicJwk(unrelatedKey, issuerJwtKid(flow.credential)))
            val holderTrust = admit(holder, flow.holderKey.publicJwk)

            val validation = validate(flow, wrongIssuerTrust, holderTrust)
            assertTrue(validation.isOk, "wrong configured JWK validation should return a result: ${if (validation.isErr) validation.error else ""}")
            assertFalse(validation.value.valid, "a wrong configured issuer JWK must fail cryptographic verification")
            assertTrue(validation.value.errors.any { it.contains("signature") || it.contains("verification") }, validation.value.errors.toString())
        }

    private suspend fun createFlow(
        aliasPrefix: String,
        version: JwtVersion = JwtVersion.V20,
        credentialTransform: suspend (String) -> String = { it },
    ): Flow {
        val issuerKey = generateKey("$aliasPrefix-issuer")
        val holderKey = provisionHolder("$aliasPrefix-holder")
        val credential = credentialTransform(issue(issuerKey.alias, version))
        val query = DcqlQuery(credentials = listOf(query(version)))
        val request =
            verifierService().createAuthorizationRequest(
                CreateAuthorizationRequestArgs(
                    instanceId = "configured-jwk-vcdm-verifier",
                    dcqlQuery = query,
                    clientId = verifier,
                    responseUri = "$verifier/response",
                    responseMode = ResponseMode.DIRECT_POST,
                    nonce = NONCE,
                    state = "configured-jwk-state",
                    clientMetadata = ClientMetadata(vpFormatsSupported = mapOf(version.format.value to jwtVcFormatInfo(listOf("ES256")))),
                ),
            ).also {
                assertTrue(it.isOk, "production verifier request command should succeed: ${if (it.isErr) it.error else ""}")
            }.value
        val resolved =
            ResolvedOid4vpRequest(
                request = request.request,
                dcqlQuery = query,
                clientMetadata = ClientMetadata(vpFormatsSupported = mapOf(version.format.value to jwtVcFormatInfo(listOf("ES256")))),
                verifierInfo = VerifierInfo(clientId = verifier, clientIdScheme = ClientIdScheme.REDIRECT_URI),
            )
        val response =
            holderService().commands.createAuthorizationResponse.execute(
                CreateAuthorizationResponseArgs(
                    request = resolved,
                    selectedCredentials =
                        listOf(
                            SelectedCredential(
                                credentialQueryId = QUERY_ID,
                                credentialId = "configured-jwk-vcdm-credential",
                                presentation = JsonPrimitive(credential),
                                credentialFormat = version.format,
                                holderKeyRef = holderKey.keyRef,
                                holderId = holder,
                                holderVerificationMethod = holderKey.kid,
                                holderJwtVpSigningIdentifier =
                                    HolderJwtVpSigningIdentifier.JwksKid(holderKey.kid),
                                holderSigningAlgorithm = SignatureAlgorithm.ECDSA_SHA256,
                                holderJwtVpOperationBinding = HOLDER_OPERATION_BINDING,
                                holderJwtVpWalletUnitId = HOLDER_WALLET_UNIT_ID,
                            ),
                        ),
                ),
            )
        assertTrue(
            response.isOk,
            "production holder must create a separately signed JWT VP: ${if (response.isErr) response.error else ""}",
        )
        return Flow(issuerKey, holderKey, credential, query, request.request, response)
    }

    private suspend fun issue(alias: String, version: JwtVersion = JwtVersion.V20): String {
        ctx.registerIssuerSigningKey(alias)
        val configuration =
            CredentialConfigurationSupported(
                format = version.format.value,
                credentialDefinition = CredentialDefinition(type = listOf("VerifiableCredential", version.credentialType)),
            )
        val graph = ctx.session.graph as VcdmConfiguredInlineJwkTestGraph
        val handler: CredentialFormatHandler = if (version == JwtVersion.V11) graph.jwtVcJsonFormatHandler else graph.vcLdJsonJwtFormatHandler
        val result = handler.issueCredential(
                CredentialRequest(format = version.format.value),
                IssuanceContext(
                    subject = "$holder/subject",
                    clientId = "configured-jwk-vcdm-client",
                    issuerIdentifier = issuer,
                    credentialConfigurationId = "configured-jwk-vcdm-credential",
                    credentialConfiguration = configuration,
                    holderBindingKey = null,
                    attributes = mapOf("level" to JsonPrimitive("gold")),
                    signingKeyAlias = alias,
                    signingKeyMode = SigningKeyMode.JwkThumbprint,
                    issuanceClockSkewInSeconds = 0,
                    expirationInDays = 30,
                ),
            )
        assertTrue(result.isOk, "production ${version.label} issuer must issue: ${if (result.isErr) result.error else ""}")
        return result.value.credential.jsonPrimitive.content
    }

    private suspend fun admit(controller: String, jwk: Jwk): TrustedAuthenticationResolution {
        val opts = ExternalIdentifierJwkOpts(identifier = jwk)
        val resolution = identifierService().resolve(opts)
        assertTrue(
            resolution.isOk,
            "production JWK identifier resolver must resolve configured material: ${if (resolution.isErr) resolution.error else ""}",
        )
        val result = assertIs<ExternalIdentifierResult.Jwk>(resolution.value)
        val resolvedJwk = assertIs<Jwk>(result.keyInfo.key)
        assertEquals(jwk.x, resolvedJwk.x, "resolved configured JWK must retain the admitted public key")
        assertEquals(jwk.y, resolvedJwk.y, "resolved configured JWK must retain the admitted public key")
        return TrustedAuthenticationResolution(controller = controller, identifier = opts)
    }

    private suspend fun validate(
        flow: Flow,
        issuerTrust: TrustedAuthenticationResolution,
        holderTrust: TrustedAuthenticationResolution,
    ) =
        verifierService().let { service ->
            val response = flow.response.value
            val parsed =
                service.parseAuthorizationResponse(
                    ParseAuthorizationResponseArgs(
                        responseParams =
                            mapOf(
                                "vp_token" to
                                    json.encodeToString(
                                        kotlinx.serialization.json.JsonElement.serializer(),
                                        VpToken.run { response.vpToken!!.toJson() },
                                    ),
                                "state" to assertNotNull(response.state),
                            ),
                        originalRequest = flow.request,
                    ),
                ).also {
                    assertTrue(it.isOk, "production response parser should accept command output: ${if (it.isErr) it.error else ""}")
                }
            service.validateAuthorizationResponse(
                ValidateAuthorizationResponseArgs(
                    parsedResponse = parsed.value,
                    originalRequest = flow.request,
                    dcqlQuery = flow.query,
                    expectedNonce = NONCE,
                    trustedAuthentications = listOf(issuerTrust, holderTrust),
                ),
            )
        }

    private suspend fun generateKey(alias: String): ManagedKeyInfoType<*> {
        val generated =
            keyManagerService().generateKeyResult(
                alias = alias,
                use = JwkUse.sig,
                alg = SignatureAlgorithm.ECDSA_SHA256,
            )
        assertTrue(generated.isOk, "software KMS key generation must succeed")
        return assertNotNull(generated.value.keyPair?.joseToManagedKeyInfo(KeyVisibility.PRIVATE))
    }

    private suspend fun provisionHolder(alias: String): HolderMaterial {
        val result =
            (ctx.session.graph as WalletInteractionOid4vciWscaTestGraph).wsca.ensureKey(
                walletUnitId = HOLDER_WALLET_UNIT_ID,
                usage = SecureComponentUsage.WALLET_CREDENTIAL_PROOF,
                algorithm = SignatureAlgorithm.ECDSA_SHA256,
                keyAlias = alias,
            )
        assertTrue(result.isOk, "holder key must be provisioned through WSCA: ${if (result.isErr) result.error else ""}")
        val key = result.value
        val publicJwk = json.decodeFromString(Jwk.serializer(), assertNotNull(key.publicKeyJwk))
        val kid = "$holder/keys/$alias"
        return HolderMaterial(
            keyRef = assertNotNull(key.keyRef, "WSCA must return an opaque holder keyRef"),
            kid = kid,
            publicJwk = publicJwk.copy(kid = kid),
        )
    }

    private suspend fun verifyRawJws(jwt: String, key: ManagedKeyInfoType<*>): Boolean {
        val parts = jwt.split('.')
        if (parts.size != 3) return false
        return keyManagerService().isValidRawSignature(
            key.toManagedPublicKeyInfo(),
            "${parts[0]}.${parts[1]}".encodeToByteArray(),
            parts[2].decodeFromBase64Url(),
        )
    }

    private fun publicJwk(key: ManagedKeyInfoType<*>, kid: String): Jwk =
        assertNotNull(key.toManagedPublicKeyInfo().key as? Jwk).copy(kid = kid)

    private fun addEmbeddedJwk(jwt: String, jwk: Jwk): String {
        val parts = jwt.split('.')
        assertEquals(3, parts.size)
        val header = json.parseToJsonElement(parts[0].decodeFromBase64Url().decodeToString()).jsonObject.toMutableMap()
        header["jwk"] = jwk.toJsonObject()
        return "${JsonObject(header).toString().encodeToByteArray().encodeToBase64Url()}.${parts[1]}.${parts[2]}"
    }

    private fun issuerJwtKid(jwt: String): String = assertNotNull(jwtHeader(jwt)["kid"]?.jsonPrimitive?.content)

    private fun jwtHeader(jwt: String): JsonObject =
        json.parseToJsonElement(jwt.substringBefore('.').decodeFromBase64Url().decodeToString()).jsonObject

    private fun jwtPayload(jwt: String): JsonObject =
        json.parseToJsonElement(jwt.split('.')[1].decodeFromBase64Url().decodeToString()).jsonObject

    private fun verifierService(): Oid4vpVerifierService =
        (ctx.session.graph as VcdmConfiguredInlineJwkTestGraph).oid4vpVerifierService

    private fun holderService(): Oid4vpHolder = (ctx.session.graph as VcdmConfiguredInlineJwkTestGraph).oid4vpHolder

    private fun identifierService(): IdentifierService =
        (ctx.session.graph as VcdmConfiguredInlineJwkTestGraph).identifierService

    private fun keyManagerService(): KeyManagerService = ctx.session.graph.asKeyManagerServiceGraph().keyManagerService

    private fun query(version: JwtVersion = JwtVersion.V20) =
        DcqlCredentialQuery(
            id = QUERY_ID,
            format = version.format.value,
            meta = w3cVcMeta(listOf("VerifiableCredential", version.credentialType)),
        )

    private fun assertCredentialShape(jwt: String, version: JwtVersion) {
        val header = jwtHeader(jwt)
        val payload = jwtPayload(jwt)
        assertEquals(version.credentialTyp, header["typ"]?.jsonPrimitive?.content)
        if (version == JwtVersion.V11) {
            assertFalse(header.containsKey("cty"))
            val vc = assertNotNull(payload["vc"] as? JsonObject)
            assertEquals(version.context, (vc["@context"] as kotlinx.serialization.json.JsonArray).first().jsonPrimitive.content)
            assertEquals(version.credentialType, (vc["type"] as kotlinx.serialization.json.JsonArray).last().jsonPrimitive.content)
            assertAnonymousCredentialSubject(vc["credentialSubject"] as? JsonObject)
            assertFalse(payload.containsKey("@context"))
        } else {
            assertEquals("vc", header["cty"]?.jsonPrimitive?.content)
            assertEquals(version.context, (payload["@context"] as kotlinx.serialization.json.JsonArray).first().jsonPrimitive.content)
            assertEquals(version.credentialType, (payload["type"] as kotlinx.serialization.json.JsonArray).last().jsonPrimitive.content)
            assertAnonymousCredentialSubject(payload["credentialSubject"] as? JsonObject)
            assertFalse(payload.containsKey("vc"))
        }
    }

    private fun assertAnonymousCredentialSubject(subject: JsonObject?) {
        val anonymousSubject = assertNotNull(subject)
        assertEquals("gold", anonymousSubject["level"]?.jsonPrimitive?.content)
        assertFalse(anonymousSubject.containsKey("id"), "credential subject must remain anonymous")
    }

    private fun assertVpShape(jwt: String, version: JwtVersion) {
        val header = jwtHeader(jwt)
        if (version == JwtVersion.V11) {
            assertEquals("JWT", header["typ"]?.jsonPrimitive?.content)
            assertFalse(header.containsKey("cty"))
        } else {
            assertEquals("vp+jwt", header["typ"]?.jsonPrimitive?.content)
            assertEquals("vp", header["cty"]?.jsonPrimitive?.content)
        }
        val payload = jwtPayload(jwt)
        if (version == JwtVersion.V11) {
            val vp = assertNotNull(payload["vp"] as? JsonObject)
            assertEquals(version.context, (vp["@context"] as kotlinx.serialization.json.JsonArray).first().jsonPrimitive.content)
            assertEquals("VerifiablePresentation", (vp["type"] as kotlinx.serialization.json.JsonArray).first().jsonPrimitive.content)
        } else {
            assertEquals(version.context, (payload["@context"] as kotlinx.serialization.json.JsonArray).first().jsonPrimitive.content)
        }
        assertEquals(NONCE, payload["nonce"]?.jsonPrimitive?.content)
        assertEquals(verifier, payload["aud"]?.jsonPrimitive?.content)
    }

    private data class Flow(
        val issuerKey: ManagedKeyInfoType<*>,
        val holderKey: HolderMaterial,
        val credential: String,
        val query: DcqlQuery,
        val request: AuthorizationRequest,
        val response: IdkResult<AuthorizationResponse, Any?>,
    )

    private data class HolderMaterial(
        val keyRef: String,
        val kid: String,
        val publicJwk: Jwk,
    )

    private enum class JwtVersion(
        val format: CredentialFormat,
        val label: String,
        val credentialType: String,
        val context: String,
        val credentialTyp: String,
    ) {
        V11(CredentialFormat.JWT_VC_JSON, "VCDM 1.1", "ConfiguredInlineJwkVcdm11Credential", "https://www.w3.org/2018/credentials/v1", "JWT"),
        V20(CredentialFormat.JWT_VC_JSON_LD, "VCDM 2.0", "ConfiguredInlineJwkVcdm2Credential", "https://www.w3.org/ns/credentials/v2", "vc+jwt"),
    }

    private companion object {
        const val QUERY_ID = "configured-inline-jwk-vcdm-query"
        const val NONCE = "configured-inline-jwk-vcdm-nonce"
        const val HOLDER_WALLET_UNIT_ID = "wallet-unit-configured-inline-jwk-vcdm-e2e"
        const val HOLDER_OPERATION_BINDING = "configured-inline-jwk-vcdm-attended-presentation"
    }
}
