/*
 * © 2026 Sphereon International B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sphereon.oauth2.server.authorization.provider

import com.sphereon.core.api.IdkResult
import com.sphereon.core.api.error.IdkError
import com.sphereon.core.compat.JsExportCompat

/**
 * Strategy for rendering the AS's first-party login surface served at `GET /login`. IDK ships a
 * single Sphereon-branded implementation; EDK overlays a tenant-aware implementation through
 * `@ContributesBinding(replaces = [...])`. The interface deliberately exposes no per-tenant or
 * registry semantics so the IDK binding can stay narrowly focused on "username + password on a
 * Sphereon-branded page".
 */
@JsExportCompat
interface LoginPageRenderer {
    /**
     * Render the login page for [ctx]. Implementations MUST escape any caller-controlled string
     * (login hint, error message) before interpolating into HTML.
     */
    suspend fun render(ctx: LoginPageContext): IdkResult<LoginPageResponse, IdkError>

    /**
     * Static assets the renderer references from its HTML (CSS, SVGs, fonts). The HTTP layer
     * mounts each one under the renderer's assets prefix and serves it with its declared
     * `Content-Type` and `Cache-Control`. Default empty so trivial implementations need only
     * override [render].
     */
    fun staticAssets(): List<LoginPageAsset> = emptyList()
}

/**
 * Inputs to [LoginPageRenderer.render]. Carries everything the renderer needs to produce a fully
 * qualified HTML response without taking the active HTTP request as an argument: AS instance,
 * tenant, the pending authorization session id (so the form can submit it back), the absolute
 * URL the AS will redirect to after successful authentication, an optional pre-fill, an optional
 * one-shot error message (for the `?error=invalid_credentials` round-trip), and a locale.
 */
@JsExportCompat
data class LoginPageContext(
    val asInstanceId: String,
    val tenantId: String?,
    val sessionId: String,
    val returnUrl: String,
    val loginHint: String? = null,
    val errorMessage: String? = null,
    val locale: String = "en",
    /**
     * Per-render anti-CSRF token bound to [sessionId]. Renderers MUST embed [tabId] and
     * [sessionCode] as hidden form inputs so the POST handler can verify the form was
     * generated by the AS for this session_id (defends against capability-URL leak — an
     * attacker who learns the URL alone cannot fabricate a valid `session_code`).
     *
     * Optional in the data class signature so legacy renderers still compile during the
     * transition; the IDK-shipped renderer reads both. A null value disables the CSRF
     * defense for that render — never do this in production.
     */
    val tabId: String? = null,
    val sessionCode: String? = null,
    /**
     * Optional informational notice rendered above the credential form (e.g. a demo deployment
     * advertising its seeded test account, or a maintenance banner). Null or blank renders
     * nothing, so production deployments that never set it carry no extra markup. The renderer
     * MUST escape this value before interpolation — it is treated as plain text, not HTML.
     */
    val notice: String? = null,
    /**
     * Federated identity providers offered as alternative sign-in options on the login page.
     * The renderer emits one button per entry, posting the visitor to the federation
     * authorize endpoint with `provider=<id>`. Empty list = render the password form only.
     *
     * Populated by the HTTP layer from [com.sphereon.oauth2.server.authorization.command.federation.ListEnabledFederationProvidersCommand],
     * filtered to the current tenant. Each entry MUST already be enabled at the registry; the
     * renderer treats the list as the final view and does no additional filtering.
     */
    val federationOptions: List<FederationLoginOption> = emptyList(),
)

/**
 * One federated provider button rendered on the login page. [id] flows into the
 * `?provider=<id>` query param at the federation authorize endpoint; [displayName] is the
 * human-readable label the renderer escapes and displays on the button. Kept narrow on
 * purpose: brand colour, icon URL, and per-provider flow hints belong in a future
 * `FederationLoginOptionTheme` overlay rather than this transport-shaped DTO.
 */
@JsExportCompat
data class FederationLoginOption(
    val id: String,
    val displayName: String,
)

/**
 * Output of [LoginPageRenderer.render]. The HTTP layer wraps this in a 200 response with the
 * declared [contentType]; [cspNonce] is reserved for a future Content-Security-Policy header that
 * pins inline scripts/styles to the same nonce. Empty [cspNonce] means the response carries no
 * inline content the renderer expects to be allow-listed.
 */
@JsExportCompat
data class LoginPageResponse(
    val html: String,
    val contentType: String = "text/html; charset=utf-8",
    val cspNonce: String? = null,
)

/**
 * A single static asset the HTTP layer must serve under the renderer's assets prefix. [path] is
 * the relative path the rendered HTML references (e.g. `css/login.css`); [bytes] is the file
 * payload; [contentType] and [maxAgeSeconds] map directly onto the `Content-Type` and
 * `Cache-Control: public, max-age=...` headers on the response.
 */
@JsExportCompat
data class LoginPageAsset(
    val path: String,
    val contentType: String,
    val bytes: ByteArray,
    val maxAgeSeconds: Long = 3600,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is LoginPageAsset) return false
        return path == other.path &&
            contentType == other.contentType &&
            maxAgeSeconds == other.maxAgeSeconds &&
            bytes.contentEquals(other.bytes)
    }

    override fun hashCode(): Int {
        var result = path.hashCode()
        result = 31 * result + contentType.hashCode()
        result = 31 * result + bytes.contentHashCode()
        result = 31 * result + maxAgeSeconds.hashCode()
        return result
    }
}
