/*
 * Copyright 2023-2026 Sphereon International B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sphereon.data.store.vault.portability

/**
 * Reserved entry layout for the versioned Vault BagIt format. The signed manifest is a BagIt
 * tag and is therefore covered by tagmanifest-sha256.txt. Policy, provenance, and optional DPV
 * context are payloads and are therefore covered by manifest-sha256.txt. Callers cannot choose
 * alternative paths for these records.
 */
object VaultBagItProfile {
    const val PROFILE_ID = "urn:sphereon:vault:bagit:1.0"
    const val PROFILE_BAG_INFO_TAG = "Vault-Profile"

    const val SIGNED_VAULT_MANIFEST_TAG = "vault-manifest.json"
    const val POLICY_SNAPSHOT_PAYLOAD = "vault-profile/policy-snapshot.json"
    const val PROVENANCE_PAYLOAD = "vault-profile/provenance.json"
    const val DPV_JSON_LD_PAYLOAD = "vault-profile/dpv.jsonld"

    val REQUIRED_ARCHIVE_ENTRIES =
        setOf(
            BagItImportValidator.BAGIT_DECLARATION,
            "bag-info.txt",
            BagItImportValidator.PAYLOAD_MANIFEST,
            BagItImportValidator.TAG_MANIFEST,
            SIGNED_VAULT_MANIFEST_TAG,
            "data/$POLICY_SNAPSHOT_PAYLOAD",
            "data/$PROVENANCE_PAYLOAD",
        )

    val RESERVED_PAYLOAD_PATHS = setOf(POLICY_SNAPSHOT_PAYLOAD, PROVENANCE_PAYLOAD, DPV_JSON_LD_PAYLOAD)

    val STRUCTURAL_REQUIREMENTS =
        BagItStructuralProfile(
            profileTagName = PROFILE_BAG_INFO_TAG,
            profileTagValue = PROFILE_ID,
            requiredTagPaths = setOf(SIGNED_VAULT_MANIFEST_TAG),
            requiredPayloadPaths = setOf("data/$POLICY_SNAPSHOT_PAYLOAD", "data/$PROVENANCE_PAYLOAD"),
        )
}

data class BagItStructuralProfile(
    val profileTagName: String,
    val profileTagValue: String,
    val requiredTagPaths: Set<String>,
    val requiredPayloadPaths: Set<String>,
) {
    init {
        require(profileTagName.isNotBlank() && profileTagValue.isNotBlank())
        require(requiredTagPaths.isNotEmpty() && requiredPayloadPaths.isNotEmpty())
    }
}

fun interface SignedVaultManifestVerifier {
    suspend fun verify(signedManifest: ByteArray): Boolean
}

data class VaultBagItProfileSource(
    val payloads: List<BagItPayload>,
    val signedVaultManifest: ReplayableVaultContent,
    val policySnapshot: ReplayableVaultContent,
    val provenance: ReplayableVaultContent,
    val dpvJsonLd: ReplayableVaultContent? = null,
    val bagInfo: Map<String, String> = emptyMap(),
)

/** Assembles the required profile records instead of relying on caller-selected file conventions. */
class VaultBagItProfileAssembler(
    private val packageBuilder: BagItPackageBuilder = BagItPackageBuilder(),
) {
    suspend fun assemble(source: VaultBagItProfileSource): BagItLogicalPackage {
        require(source.signedVaultManifest.sizeBytes > 0) { "Signed vault manifest must not be empty" }
        require(source.policySnapshot.sizeBytes > 0) { "Policy snapshot must not be empty" }
        require(source.provenance.sizeBytes > 0) { "Provenance must not be empty" }
        source.dpvJsonLd?.let { require(it.sizeBytes > 0) { "DPV JSON-LD must not be empty when supplied" } }
        require(source.bagInfo.keys.none { it.equals(VaultBagItProfile.PROFILE_BAG_INFO_TAG, ignoreCase = true) }) {
            "${VaultBagItProfile.PROFILE_BAG_INFO_TAG} is generated by the vault profile"
        }

        val collisions = source.payloads.map { VaultPortablePath.collisionKey(it.path) }.toSet()
        VaultBagItProfile.RESERVED_PAYLOAD_PATHS.forEach { reserved ->
            require(VaultPortablePath.collisionKey(reserved) !in collisions) { "Payload path '$reserved' is reserved by the vault profile" }
        }

        val profilePayloads =
            buildList {
                add(ProfilePayload(VaultBagItProfile.POLICY_SNAPSHOT_PAYLOAD, source.policySnapshot))
                add(ProfilePayload(VaultBagItProfile.PROVENANCE_PAYLOAD, source.provenance))
                source.dpvJsonLd?.let { add(ProfilePayload(VaultBagItProfile.DPV_JSON_LD_PAYLOAD, it)) }
            }
        val packageSource =
            packageBuilder.build(
                payloads = source.payloads + profilePayloads,
                bagInfo = source.bagInfo + (VaultBagItProfile.PROFILE_BAG_INFO_TAG to VaultBagItProfile.PROFILE_ID),
                reservedTags =
                    listOf(
                        BagItReservedTagEntry(
                            path = VaultBagItProfile.SIGNED_VAULT_MANIFEST_TAG,
                            content = source.signedVaultManifest,
                        ),
                    ),
            )
        val actual = packageSource.entries.mapTo(mutableSetOf()) { it.path }
        check(actual.containsAll(VaultBagItProfile.REQUIRED_ARCHIVE_ENTRIES)) { "Incomplete Vault BagIt profile" }
        return packageSource
    }

    private data class ProfilePayload(
        override val path: String,
        override val content: ReplayableVaultContent,
    ) : BagItPayload {
        override val contentClass: VaultExportContentClass = VaultExportContentClass.PORTABLE_DATA
    }
}

/** Structural-only inspection with a name that does not imply signature verification. */
class VaultBagItStructuralValidator(
    checksumProvider: VaultChecksumProvider = Sha256VaultChecksumProvider(),
    limits: VaultImportLimits = VaultImportLimits(),
    excludedPathSegments: Set<String> = VaultExportExclusionPolicy.DEFAULT_EXCLUDED_SEGMENTS,
) {
    private val validator =
        BagItImportValidator(
            checksumProvider = checksumProvider,
            limits = limits,
            excludedPathSegments = excludedPathSegments,
            structuralProfile = VaultBagItProfile.STRUCTURAL_REQUIREMENTS,
        )

    suspend fun verify(archive: VaultArchiveSource): VaultPackageVerificationResult = validator.verify(archive)
}

/**
 * Fail-closed Vault BagIt profile verification. No local signature or OpenTDF substitute is used: when the
 * provider-specific [signedManifestVerifier] is absent, verification returns an explicit issue.
 */
class VaultBagItProfileVerifier(
    checksumProvider: VaultChecksumProvider = Sha256VaultChecksumProvider(),
    limits: VaultImportLimits = VaultImportLimits(),
    excludedPathSegments: Set<String> = VaultExportExclusionPolicy.DEFAULT_EXCLUDED_SEGMENTS,
    signedManifestVerifier: SignedVaultManifestVerifier? = null,
) {
    private val validator =
        BagItImportValidator(
            checksumProvider = checksumProvider,
            limits = limits,
            excludedPathSegments = excludedPathSegments,
            structuralProfile = VaultBagItProfile.STRUCTURAL_REQUIREMENTS,
            signedManifestVerifier = signedManifestVerifier,
            requireSignedManifestVerification = true,
        )

    suspend fun verify(archive: VaultArchiveSource): VaultPackageVerificationResult = validator.verify(archive)
}
