/*
 * © 2026 Sphereon International B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

package com.sphereon.trust.core

/** Stable machine-readable reasons for fail-closed trust decisions. */
object TrustDiagnosticReasonCodes {
    const val SIGNER_ROOT_NOT_CONFIGURED = "SIGNER_ROOT_NOT_CONFIGURED"
    const val EMBEDDED_CERTIFICATE_NOT_TRUSTED = "EMBEDDED_CERTIFICATE_NOT_TRUSTED"
    const val SIGNER_CHAIN_INVALID = "SIGNER_CHAIN_INVALID"
    const val SIGNATURE_INVALID = "SIGNATURE_INVALID"
    const val UNSUPPORTED_CRITICAL_HEADER = "UNSUPPORTED_CRITICAL_HEADER"
    const val SERIALIZATION_NOT_LOSSLESS = "SERIALIZATION_NOT_LOSSLESS"
    const val TRUST_LIST_EXPIRED = "TRUST_LIST_EXPIRED"
    const val TRUST_LIST_SEQUENCE_ROLLBACK = "TRUST_LIST_SEQUENCE_ROLLBACK"
    const val TRUST_LIST_NEXT_UPDATE_EXPIRED = "TRUST_LIST_NEXT_UPDATE_EXPIRED"
    const val TRUST_LIST_RESOLUTION_FAILED = "TRUST_LIST_RESOLUTION_FAILED"
    const val TRUST_LIST_TARGET_REJECTED = "TRUST_LIST_TARGET_REJECTED"
    const val TRUST_LIST_URL_MALFORMED = "TRUST_LIST_URL_MALFORMED"
    const val TRUST_LIST_URL_REJECTED = "TRUST_LIST_URL_REJECTED"
    const val TRUST_LIST_ADDRESS_BLOCKED = "TRUST_LIST_ADDRESS_BLOCKED"
    const val TRUST_LIST_ADDRESS_RESOLUTION_FAILED = "TRUST_LIST_ADDRESS_RESOLUTION_FAILED"
    const val TRUST_LIST_DNS_REBINDING = "TRUST_LIST_DNS_REBINDING"
    const val TRUST_LIST_REDIRECT_MISSING = "TRUST_LIST_REDIRECT_MISSING"
    const val TRUST_LIST_REDIRECT_MALFORMED = "TRUST_LIST_REDIRECT_MALFORMED"
    const val TRUST_LIST_REDIRECT_LIMIT = "TRUST_LIST_REDIRECT_LIMIT"
    const val TRUST_LIST_REDIRECT_DOWNGRADE = "TRUST_LIST_REDIRECT_DOWNGRADE"
    const val TRUST_LIST_POINTER_MISSING = "TRUST_LIST_POINTER_MISSING"
    const val CERTIFICATE_NOT_FOUND = "CERTIFICATE_NOT_FOUND"
    const val SERVICE_REVOKED = "SERVICE_REVOKED"
    const val SERVICE_STATUS_UNKNOWN = "SERVICE_STATUS_UNKNOWN"
    const val TRUST_LIST_BODY_TOO_LARGE = "TRUST_LIST_BODY_TOO_LARGE"
    const val TRUST_LIST_RESOLUTION_TIMEOUT = "TRUST_LIST_RESOLUTION_TIMEOUT"
    const val TRUST_LIST_HTTP_STATUS = "TRUST_LIST_HTTP_STATUS"
    const val TRUST_LIST_CACHE_EXPIRED = "TRUST_LIST_CACHE_EXPIRED"
    const val TRUST_LIST_CACHE_REVALIDATION_REQUIRED = "TRUST_LIST_CACHE_REVALIDATION_REQUIRED"
}
